### ISSUE TITLE
Bad changelog entry for 6.0.0 on current master

### ISSUE THREAD

**Issue by noirbizarre** [getsentry/raven-python#1001]
When #964 has been updated for being merged, [the changelog entry has been left into the 6.0.0 release](https://github.com/getsentry/raven-python/blob/master/CHANGES#L16-L17) which was released between the PR submission and the merge.
This change hasn't been released yet and should be in a new changelog section (6.0.1 ?)

**Comment by ashwoods** [comment]
Wandered into 6.10
