### ISSUE TITLE
Segmentation fault when running Flask development server in Alpine Linux

### ISSUE THREAD

**Issue by rossgray** [getsentry/raven-python#1003]
Hi,

I am getting a segmentation fault when using Raven with the Flask development server on Alpine Linux. Oddly, this issue only appears to occur when I install a recent version of the `requests` library (>= v2.13.0) (even if I don't import that library in my code). This issue is only specific to Alpine - it works fine on other Python Docker images. The issue occurs on versions of Raven >= 5.4.0.

I think the segmentation fault is related to some imports within the Raven library.
When I change the following lines it fixes the problem:
https://github.com/getsentry/raven-python/blob/master/raven/conf/remote.py#L18-L19

from:

```py
from raven.transport.threaded import ThreadedHTTPTransport
from raven.transport.http import HTTPTransport
```

to:

```py
from raven.transport import ThreadedHTTPTransport
from raven.transport import HTTPTransport
```

i.e. remove the submodule, which isn't needed since in `transport/__init__.py` there is:

```py
from raven.transport.http import *  # NOQA
```

I have created a test project to reproduce this issue:
https://github.com/ingresso-group/flask-raven-debug

**Environment:**
- `python:3.6-alpine` Docker image
- Python 3.6.1
- Flask 0.12
- Werkzeug 0.12.1
- Raven 6.0.0

**Comment by beaugunderson** [comment]
There are two additional open issues that involve `python:3.6-alpine` and threading:

- https://github.com/docker-library/python/issues/211
- https://github.com/esnme/ultrajson/issues/254

I think the root cause for this issue and the other two is the same (and I'm offering a $100 bounty for docker-library/python#211)

**Comment by beaugunderson** [comment]
@rossgray based on the research from the other issues I'm confident that this is an issue with musl's smaller default stack size; you can try [this workaround](https://github.com/esnme/ultrajson/issues/254#issuecomment-314862445) or try upgrading to `requests>=2.18.1`, which does not suffer from the segfault in my experience (but you may still experience it if you use other dependencies, especially ones that include `ultrajson`).

**Comment by beaugunderson** [comment]
[here's a link to some background discussion on increasing the stack size in musl](https://github.com/voidlinux/void-packages/issues/4147), for reference.

**Comment by rossgray** [comment]
Thank you @beaugunderson ! I can confirm that upgrading to requests 2.18.1 resolves the issue (at least for now)
