### ISSUE TITLE
don't just ignore oversized stack frame local in get_frame_locals

### ISSUE THREAD

**Issue by agroszer** [getsentry/raven-python#1008]
```
def get_frame_locals(frame, transformer=transform, max_var_size=4096):
...
    for k, v in iteritems(f_locals):
        v = transformer(v)
        v_size = len(repr(v))
        if v_size + f_size < 4096:
            f_vars[k] = v
            f_size += v_size
```

That will just leave out the oversized variable WITHOUT ANY NOTICE. Come on! If it's oversized at least add ```f_vars[k] = "<Value omitted because it's too big>"```. Otherwise I can debug all day why it's missing.

BTW, the `max_var_size` parameter seems to be a decoy here.

**Comment by agroszer** [comment]
on the second look it's also random... whichever next variable repr + existing length is over 4096 gets dropped

**Comment by dcramer** [comment]
The server filters down events to a maximum specific size, and we cannot truncate them to a native representation. There are other tickets tracking this so I'm closing this out.

**Comment by agroszer** [comment]
could you link the other ticket(s)?

**Comment by agroszer** [comment]
https://github.com/getsentry/raven-python/issues/679

**Comment by agroszer** [comment]
Also, is there any chance to configure the server side? We're hosting our own sentry server.

**Comment by dcramer** [comment]
@agroszer possibly, but id suggest not as theres a point where we probably remove the tuning configuration here so everything can maintain its standards
