### ISSUE TITLE
Is raven_compat needed anymore?

### ISSUE THREAD

**Issue by dwaynebailey** [getsentry/raven-python#1015]
All the docs seem to reference imports as e.g.:

```python
from raven.contrib.django.raven_compat.models import sentry_exception_handler
```

While:

```python
from raven.contrib.django.models import sentry_exception_handler
```

Seems to work just fine.  Is `raven_compat` strictly needed, or is it a backward compatability fix that just never got updated?  If it isn't needed it would be great to cleanup the docs.

**Comment by dcramer** [comment]
Django doesn't (or didn't) support apps with the same trailing name. We created raven_compat as a 'unique' app name for Django.
