### ISSUE TITLE
Breadcrumbs in Raven

### ISSUE THREAD

**Issue by prasantarmaye** [getsentry/raven-python#1019]
Hi,

I am using Raven in my openERP project to log to Sentry. During this, I have observed that the breadcrumbs limit cannot be set by the client through the API. I can only enable_breadcrumbs or disable them. I would like to log breadcrumbs for ERROR only.

To summarise, I am looking forward to:
1. Set the limit for number of breadcrumbs from client.
2. To log breadcrumbs for specific log levels.

Below is additional information:
I have gone through the Raven package and understood that we are getting breadcrumbs if below statement is true-
# insert breadcrumbs
if self.enable_breadcrumbs:

Also breadcrumbs limit is set to 100, in breadcrumbs.py that can't be changed by client.

Please let me know if we have a workflow to get these items through the API else, can these changes be provided in your upcoming releases.

Thanks,
Prasantarmaye

**Comment by prasantarmaye** [comment]
Hi,

I am still waiting from Raven team to hear. It is urgent for us.

Thanks,
Prasantarmaye

**Comment by ashwoods** [comment]
We will take a look at making the breadcrumb buffer limit easier to configure. 
You can control the logging instrumentation by registering a [handler](https://docs.sentry.io/clients/python/breadcrumbs/#enabling-disabling-instrumentation) using `register_logging_handler`.
