### ISSUE TITLE
[flask] app.logger log call messages are not send to sentry

### ISSUE THREAD

**Issue by brodul** [getsentry/raven-python#1030]
I am researching how python raven behaves in a flask app. And I encountered some weird behavior.

# Issue
I initialize sentry/raven with
`sentry = Sentry(app, logging=True, level=logging.ERROR)`
If I call for example `app.logger.error('App logger error')` the message is not reported back to sentry.
But if I use `logger.error('Generic logger error')` where the `logger` object is returned by `getLogger`, the message is send to sentry.

Why is the `app.logger.error` call not registered? Is this expected?

# Versions
```
Flask==0.12.2
raven==6.1.0
```

# How to reproduce

You need to set the DSN.

``` python
import logging

from flask import Flask
from raven.contrib.flask import Sentry


logger = logging.getLogger(__name__)
app = Flask(__name__)


@app.route("/")
def hello():
    return "Hello World!"

sentry = Sentry(app, logging=True, level=logging.ERROR)


logger.error('Logger error')

app.logger.error('App logger error')
```
https://github.com/brodul/flask_logging_research/blob/bug_report/simple_app.py

**Comment by ashwoods** [comment]
Afaik the sentry integration doesn't register the sentry handler automatically with the app.logger, as seen here: http://flask.pocoo.org/docs/0.12/errorhandling/#logging-to-a-file

Could you try registering raven.handlers.logging.SentryHandler to the app.logger and see if that works? If it was a deliberate design decision, not sure yet.

**Comment by brodul** [comment]
@ashwoods the funky stuff is that the handler is registered to the parent logger.
```
ipdb> app.logger.parent
<logging.RootLogger object at 0x7f513f69e588>
ipdb> app.logger.parent.handlers
[<raven.handlers.logging.SentryHandler object at 0x7f513ac4cf28>]
```

**Comment by dcramer** [comment]
I'm seeing this as well in a clean Flask install (https://github.com/getsentry/zeus). Going to more or less say it's broken.

**Comment by ashwoods** [comment]
@brodul wouldn't you want it to be registered at the root logger too? 

 by default app.logger.propagate is set to False, which will prevent the errors to propagate to sentry with the default configuration.

**Comment by dcramer** [comment]
@ashwoods the problem is the flask logger (i can only assume) may be setting propagate=False, and given we are explicitly setting "configure logging", I'd expect it to also apply to app.logger
