### ISSUE TITLE
Detecting if is_authenticated is a method causes deprecation warnings

### ISSUE THREAD

**Issue by ChaosMTA** [getsentry/raven-python#1035]
Note the implementation you made for the client [here](https://github.com/getsentry/raven-python/blob/d8d3c834b7d3792bdef93a55e876ace1630579c6/raven/contrib/django/client.py#L150)

This is a problem because it will cause a deprecation warning every time the module runs a logger. 

I have a special case where I have to manage a large website. I use raven to send logging events when it detects a deprecation warning, this will cause it to send another deprecation warning event from the module itself.
![](http://i.imgur.com/drrKVYt.png)

Since technically in Django 1.11, `is_authenticated()` is still valid until it is fully phased out in 2.0.

Wouldn't a check for this be more effected like:
```python
            if hasattr(user, 'is_authenticated'):
                authenticated = user.is_authenticated
            elif callable(user.is_authenticated):
                # Django < 1.11
                authenticated = user.is_authenticated()
            elif not authenticated:
                return None
```

**Comment by bbayles** [comment]
The deprecation warnings are a nuisance, so +1 here.

Another consideration: it would be better to check what path to take at import time, rather than re-checking it during each call.

For example, something like this at the top of the file could replace the current checks.

```
from django import VERSION as DJANGO_VERSION

if DJANGO_VERSION < (1, 10):
    def _is_authenticated(request_user):
        return request_user.is_authenticated()
else:
    def _is_authenticated(request_user):
        return request_user.is_authenticated
```
