### ISSUE TITLE
Is the sentry client object safe to make multiples of?

### ISSUE THREAD

**Issue by Daenyth** [getsentry/raven-python#1044]
I'm looking at using sentry client api a little more heavily in my application and I'm wondering whether it's reasonable to create multiple client objects, or whether I should create a single client object that gets passed through the app. Is there a recommended pattern here? Specifically for uses like custom sentry alerts, breadcrumbs, etc.

**Comment by dcramer** [comment]
It should work just fine and its intended to work as an instance vs singleton

**Comment by Daenyth** [comment]
Thanks!
