### ISSUE TITLE
Offline?

### ISSUE THREAD

**Issue by vidstige** [getsentry/raven-python#1046]
I've got a python program running on embedded linux machines all over the globe. I would like to add some kind of error tracking and sentry web interface seems awesome. However, the machine may or may not be online, but it seems Raven only handles the scenario where the machine running the python program has internet access. I would like it to

1. Encode message to be sent to API
2. Save it on disk
3. Send it to server
4. Remove from disk

And then e.g. on startup or periodically (there could be an SDK call perhaps?) it would try to flush saved crashes to sentry.io.

Is this reasonable? Are there any wrappers around raven to enable this? Is sentry.io right for me? Thanks in advance.

**Comment by ashwoods** [comment]
the python sdk doesn't support spooling or buffering, although the mobile sdk's do. sentry.io the server handles it fine. I'll look into it this week, don't think that a small buffering wrapper should be very hard.

**Comment by vidstige** [comment]
Thanks for clarifying this. I would be very grateful if you had time to look into this. I would really want to use your service rather than spending time & money rolling my own. :+1:

**Comment by vidstige** [comment]
Let me know if you need any help coding things up or feedback on partial work or whatever.

**Comment by vidstige** [comment]
Not much left on the week. How has things been going?

**Comment by dcramer** [comment]
@vidstige his can easily be implemented by extending our client transports. You'd just need to understand what offline state is and respond to changes. 

If you really think it's easier to replace the 100k+ loc and 10 years of experience Sentry has than doing that I wish you the best of luck :)

**Comment by vidstige** [comment]
@dcramer no, I don't think that would be easier. I'm trying to avoid this, hence this issue. :-) However, I _have_ written things like this in the past so it's definitely an option.

Thanks for your pointers, I will look into it next week. Could you give any further details? What source files can be interesting for me if I want to learn what "offline state" is?

**Comment by vidstige** [comment]
Wait, what do you mean with 100k+ loc? Sounds like bloated enterprise software to me. Perhaps I should roll my own after all. :thinking:

**Comment by dcramer** [comment]
@vidstige Sentry doesnt just say "take this stacktrace and store in in the database" and that kind of comment is not wanted or needed on our issue tracker.

To do what I said, you should look at raven.transports, as there's a 'send' mechanism. In your simplistic use case above, you'd simply write to disk on send, delete on success, and re-send queued on-disk objects when the transport is initialized.

**Comment by vidstige** [comment]
@dcramer sorry, I didn't mean to offend you or your team. Just trying understand if sentry is for me or no. Realize even a perfectly fine product is not suitable for _all_ use cases. It seems it's almost there, and now I want to help you guys out by making a pr for this. Thanks again for your help! 👍

**Comment by dcramer** [comment]
@vidstige I promise you won't be disappointed :)

(we have on our TODO to implement an offline capable abstraction for our SDK spec, we're just not there yet)

**Comment by ashwoods** [comment]
@vidstige my weeks normally end on Sunday. I was taking a look at what solutions we can provide for this in the python SDK, but I don't think we should provide more than the sync/send abstraction, as the "check for connectivity" at the python level would be... somewhat hacky and probably better implemented for each case by the user.
