### ISSUE TITLE
Possible core bug with payload size due to infinite Error stack trace limit results in 413 err

### ISSUE THREAD

**Issue by niftylettuce** [getsentry/raven-python#1050]
Hi @benvinegar - I'm wondering if this is an issue with `raven` or something on my end.

I'm using the standard default Express setup with `raven`'s `requestHandler` middleware, but for some reason I constantly get `raven@2.1.0 alert: failed to send exception to sentry: HTTP Error (413): undefined` errors.  This is a `413` is Payload Too Large error.

Related to #339 and #58.  Since we set `Error.stackTraceLimit = Infinity;` at https://github.com/getsentry/raven-node/blob/514159d8b2bf173ed70beafba786a1087c7ceaa5/index.js#L9-L10 does this cause this issue?

**Comment by niftylettuce** [comment]
@benvinegar just updated the title/message here, sorry for confusion if any, was from a copy paste I was working on

**Comment by benvinegar** [comment]
> `Error.stackTraceLimit = Infinity`

Yeah, I don't see that we limit the stack trace elsewhere, so this may be the cause. I know that we have a limit of, say, 50 frames in Raven.js.

**Comment by benvinegar** [comment]
Wait, this is `raven-python`. Did you intend to open on this project?

**Comment by niftylettuce** [comment]
![doh](https://media.giphy.com/media/TwtXMS5EnKDBK/giphy.gif)

**Comment by niftylettuce** [comment]
@benhodgson see https://github.com/getsentry/raven-js/issues/1004
