### ISSUE TITLE
Expect logging._srcfile to be None

### ISSUE THREAD

**Issue by MarcSchmitzer** [getsentry/raven-python#1051]
The `breadcrumbs` module uses the `logging._srcfile` attribute and crashes if it is `None`. The `logging` module sort of allows this, though:

> \# _srcfile is only used in conjunction with sys._getframe().
> \# To provide compatibility with older versions of Python, set _srcfile
> \# to None if _getframe() is not available; this value will prevent
> \# findCaller() from being called.

We use a third party library that actively sets `logging._srcfile` to `None`. I'm aware that asking raven to consider this is rather weird, but I thought I'd at least ask :smile: 

I can provide a simple patch that makes `_wrap_logging_method` bail in that case, if there is interest.

**Comment by dcramer** [comment]
IMO our SDK should always be defensive. I'm not sure if this is causing a hard error but:

- it should only log errors and never fail
- we should support odd environments to the best of our ability (do a patch here is fine)

**Comment by ashwoods** [comment]
Fixed in #1053
