### ISSUE TITLE
Add basic AWS lambda

### ISSUE THREAD

**Issue by ashwoods** [getsentry/raven-python#1057]

**Comment by donalt** [comment]
Hi, we're currently using https://github.com/Netflix-Skunkworks/raven-python-lambda on our Lambda functions and would be happy to help getting this into Raven proper, if you need it.

**Comment by ashwoods** [comment]
Currently, this is the branch: https://github.com/getsentry/raven-python/tree/lambda-integration that is based on the raven-python-lambda package. 

While the decorator works, I'm a little unhappy releasing the integration this way as it is somewhat fragile. As lambda ignores sys.excepthook, we can't initialize sentry "early" enough to catch common initialization errors that can happen after a deploy. I'm considering an API in which we provide a handler that then, in turn, initializes the rest.
