### ISSUE TITLE
Just a question not issue

### ISSUE THREAD

**Issue by hmilkovi** [getsentry/raven-python#1071]
Hello,
I really enjoy this package but I need info what is estimated date for release that
fully supports Django 1.11.

For now with v6.1.0 i have Issue that the ` manage.py raven test ` returns 404 when
sending ` test_message ` to server. If needed more info on this let me know.

I have a project that will soon go in production so just for sake of project management
that I know should I downgrade Django or wait.

Thx.

**Comment by dcramer** [comment]
Is it not working for you on django 1.11?

**Comment by ashwoods** [comment]
1 week later as planned :) 
master only has a few minor open issues, which I'll merge in this week and release.

**Comment by hmilkovi** [comment]
Thx great :)
