### ISSUE TITLE
Importing `from raven.contrib.flask import Sentry` leads to RuntimeError because blinker is missing

### ISSUE THREAD

**Issue by MartinThoma** [getsentry/raven-python#1075]
I followed the instructions of `Sentry` and added

    from raven.contrib.flask import Sentry
    sentry = Sentry(app, dsn='https://my_dsn')

to my code. I've got

    RuntimeError: signalling support is unavailable because the blinker library is not installed

Installink [blinker](https://pypi.python.org/pypi/blinker)

    sudo -H pip install blinker

fixed it. Should blinker be added to the `requirements.txt` of raven?

**Comment by ashwoods** [comment]
Did you install raven like this?

pip install raven[flask]

**Comment by ashwoods** [comment]
@MartinThoma I'd say so :)

**Comment by look4regev** [comment]
Thanks guys. Worth mentioning here that in the new `sentry-sdk` standard lib, it has been added to the docs:
https://docs.sentry.io/platforms/python/flask/
(`pip install -U "sentry-sdk[flask]"`)

**Comment by nandakarvapaly** [comment]
True, installing with flask as extras solved the issue for me.
