### ISSUE TITLE
Django WSGIRequest's data is not sanitized at all by SanitizeProcessor

### ISSUE THREAD

**Issue by yevhen-m** [getsentry/raven-python#1080]
`python 3.6.2`
`Django==1.11.4`
`raven==6.1.0`

`DjangoClient` captures request data from `WSGIRequest`. It's `body` attribute holds a `bytes` object, so body is skipped in `SanitizeProcessor` cause it's not an instance of `string_types` which is `str` for `python3`. This might cause sensitive data to be sent to sentry server unmasked!

**Comment by ashwoods** [comment]
@yevhen-m thx for the report.  I'll look into it.

**Comment by prokaktus** [comment]
@yevhen-m it should be fixed in `master` now.
