### ISSUE TITLE
Why is first client stored in global Raven variable?

### ISSUE THREAD

**Issue by hiir** [getsentry/raven-python#1088]
Hello,

I am confused why is first Raven Client is stored in global Raven variable in base.py module. It is not used anywhere as far I can tell from code and is not even exported from module. It is commented as "singelton", which it is not as it does not prevent creation of new Client instances.

base.py
```
# singleton for the client
Raven = None
..

class Client(object):
    def __init__(self, dsn=None, raise_send_errors=False, transport=None,
                 install_sys_hook=True, **options):
        global Raven
...
        if Raven is None:
            Raven = self
```

Relevant commit from 2013:
https://github.com/getsentry/raven-python/commit/2c3acebf9ff882de0ea3b2db4b3bd2b1c5b3ed62

**Comment by dcramer** [comment]
@hiir its a convenience tool so the client can be referenced automatically in some systems. I'm not sure its very widely used.

**Comment by hiir** [comment]
Ok, thanks for clarification. I was confused as __all__ did not export it, but if it is imported explicitly then it indeed has convenience value.

I also noticed that if one creates multiple Client instances, then the Raven variable is assigned first Client instance, but install_sys_hook uses *last* Client instance which was created. Due this there is always two Client instances left to hang around even when otherwise not used anymore (out of scope) - one via global Raven variable, another via closure assigned to sys.excepthook.
