### ISSUE TITLE
Ho can i send custom data with  client.captureException()?

### ISSUE THREAD

**Issue by awesomehimanshu** [getsentry/raven-python#1093]
```
CREATE OR REPLACE FUNCTION public.ravenlog(a integer)
    RETURNS integer
    LANGUAGE 'plpythonu'
    COST 100.0
    VOLATILE 
   AS 
 $function$
from raven import Client
client = Client('__DSN__')
try:
 1 / 0
except ZeroDivisionError as err:
 client.captureException()
return a
$function$;
```

I want to add custom data with 
client.captureException()
like some json data . How can i do so ?
Thanks

**Comment by ashwoods** [comment]
You can pass `extra` to `client.captureException` with a `dict` for example.

**Comment by awesomehimanshu** [comment]
@ashwoods  can you tell by code client.captureException() . How?
Please can you write code and can you provide docs?

**Comment by ashwoods** [comment]
`client.captureException(extra={'foo':'bar'})` if you want to pass a dictionary for example.

**Comment by awesomehimanshu** [comment]
Is there is doc for this , i don't find any thing ? I have to pass whole object .

**Comment by awesomehimanshu** [comment]
Thanks @ashwoods .

**Comment by awesomehimanshu** [comment]
```
try:
 raise ValueError('Error in postgres function.')
except ValueError as err:
 client.captureException(extra={'app_id': '1000', 'package': 'data'})   
``` 
How can i add custom error ? Actually when i do so it send extra data but i want the error type should be change?

Like it is logging valuError in mail but i want it to give name of error i want? I want to modify error object  also.

I can i do ?

**Comment by ashwoods** [comment]
I think what you want is to customise your exception. Take a look at this [stackoverflow question](https://stackoverflow.com/questions/1319615/proper-way-to-declare-custom-exceptions-in-modern-python) for examples.

**Comment by awesomehimanshu** [comment]
thanks man.that completely solve my problem
