### ISSUE TITLE
How to pass custom data with raven-python?

### ISSUE THREAD

**Issue by awesomehimanshu** [getsentry/raven-python#1094]
@ashwoods where to pass extra or dict . 
can you tell by code client.captureException() . How?
Please can you write code and can you provide docs?

Thanks for quick reply.

```
from raven import Client
client = Client('__DSN__')
try:
 1 / 0
except ZeroDivisionError as err:
 client.captureException()
```
how to pass custom error and data in client.captureException().

You answer
https://github.com/getsentry/raven-python/issues/1093

**Comment by ashwoods** [comment]
@awesomehimanshu No need to open an issue for every question.
