### ISSUE TITLE
Are any way to add custom tags for sentry_exception_handler in Django?

### ISSUE THREAD

**Issue by artefactop** [getsentry/raven-python#1103]
I want to pass some custom tags to sentry in Django and I'm using `sentry_exception_handler`.

What is the best way to do it?

Thanks

**Comment by ashwoods** [comment]
The best option is to subclass the Client. Take a look at `raven.contrib.django.client` to see how we add tags.

**Comment by artefactop** [comment]
I found the way, thank you!
