### ISSUE TITLE
Sentry and multiprocessing?

### ISSUE THREAD

**Issue by hitmeupallthetime** [getsentry/raven-python#1110]
I can't get multiprocessing spawned worker functions to work with sentry when the worker functions raises an exception.

With below code, I expect both of the spawned worker_function to separately send logs to sentry when the ZeroDivisionError is raised. However, sentry doesn't appear to send any logs at all. Am I missing something, or this is not how it works. Cheers.

```
import multiprocessing

dsn = 'https://xxx:yyy@sentry.io/zzzz'

def worker_function():
    from raven import Client
    client = Client(dsn)
    print("worker crashes")
    1 / 0

def manager_function():
    workers_count = 2
    workers = [multiprocessing.Process(target=worker_function) for i in range(workers_count)]
    for worker in workers:
        worker.start()

manager_function()
```

**Comment by ashwoods** [comment]
Sentry handling exceptions by default works by using `sys.excepthook`, which doesn't work with threading and multiprocessing due to [python issue 1230540](https://bugs.python.org/issue1230540). Workarounds exist but a bit tricky. Wrapping your code in a try and using `client.CaptureException` should work fine. A long term fix is already on our radar.

**Comment by hitmeupallthetime** [comment]
A solution can be found below. I monkeypatched multiprocessing run, then used the synchronous transport (the async doesn't work, because it needs to send the pending request when the process ends, but the hook isn't there).

`
import multiprocessing
import threading
import sys
from raven import Client
from raven.transport.requests import HTTPTransport

dsn = "xx"


def install_thread_excepthook():
    """
    Workaround for sys.excepthook thread bug
    (https://sourceforge.net/tracker/?func=detail&atid=105470&aid=1230540&group_id=5470).
    Call once from __main__ before creating any threads.
    If using psyco, call psycho.cannotcompile(threading.Thread.run)
    since this replaces a new-style class method.
    """
    start_old = multiprocessing.Process.run
    def run(*args, **kwargs):
        client = Client(dsn, transport=HTTPTransport)
        try:
            start_old(*args, **kwargs)
        except (KeyboardInterrupt, SystemExit):
            raise
        except:
            client.captureException()
    multiprocessing.Process.run = run

install_thread_excepthook()

def worker_function():

    print("worker crashes")
    1 / 0

def manager_function():
    workers_count = 2
    workers = [multiprocessing.Process(target=worker_function) for i in range(workers_count)]
    for worker in workers:
        worker.start()

manager_function()
`

**Comment by nevmerzhitsky** [comment]
idk about the proposed reason and solution of the issue, but another one can be an async transport which used by default by raven lib. Details and solution can be found here: https://stackoverflow.com/questions/44173252/how-to-configure-sentry-to-send-exception-from-process-spawned-by-python-multipr

**Comment by erpheus** [comment]
For those working with the new sentry_sdk library. I managed to not have to change the http transport by adding a call to flush after the capture_exception. Had no need to create a new hub/client, although that might be necessary to not leak context between processes, haven't tested that.

```python
from sentry_sdk import capture_exception, flush
from multiprocessing import Process

def f():
    pass

def safe_f(*args, **kwargs):
    try:
        f(*args, **kwargs)
    except Exception as e:
        capture_exception(e)
        flush()
        raise

p = Process(target=safe_f)
p.start()
```

**Comment by Randomneo** [comment]
@ashwoods is this still actual? How about "long term fix is already on our radar"?)

**Comment by ashwoods** [comment]
@Randomneo `python-raven` has been deprecated for a while. The recommended approach is to have a hub for each "concurrency" unit, but you can take a look at the `threading` integration or `with hub` if you want to see how to propagate context.
