### ISSUE TITLE
passing user identifiers with the python.logging handler

### ISSUE THREAD

**Issue by bendog** [getsentry/raven-python#1123]
you can pass tags with raven's logging handler with 
`log.error('error message', extra={'tags': {'server': SERVERNAME}`

I haven't been able to get user identifying details working with any of the examples, perhaps it should be handled in a similar way to the tags method.
`log.error('error message', extra={'user': {'username': USERNAME, 'email': USER_EMAIL}`

**Comment by bendog** [comment]
looks like PR #1082 resolves this.

**Comment by bendog** [comment]
could someone please have a look at this pull request?

**Comment by dcramer** [comment]
I’m in with that but really we should be relying on context methods and push ourselves away from logging.

**Comment by bendog** [comment]
the issue I have is that the logger being used is in a scope larger than the class which understands who the user is, so I can't change the context for the whole logger, I need to pass the context inside the error being generated. 
is there another way to do this?

**Comment by bendog** [comment]
is there anything I can do to help with this?

**Comment by ashwoods** [comment]
I'll merge this today, as it doesn't hurt. wouldn't mind a test though.

**Comment by bendog** [comment]
I've been running it on a few of my production scripts, so it seems to be handling it pretty well on both py2.7 and 3.5, i wouldn't consider this comprehensive testing
