### ISSUE TITLE
Support for Django 2.0 URL Resolver

### ISSUE THREAD

**Issue by ikosenn** [getsentry/raven-python#1127]
Django 2.0 has changed its routing. The resolver throws an ``Attribute Error`` in a bunch of places.

**Comment by ikosenn** [comment]
![screen shot 2017-11-03 at 01 53 37](https://user-images.githubusercontent.com/5145715/32366484-7e05284c-c03b-11e7-8056-07c4dd06a12b.png)

**Comment by dkaranja** [comment]
+1

**Comment by khakulov** [comment]
Django 2.0 is already relased. This bug is now blocking our upgrade to Django 2.0.

**Comment by wooyek** [comment]
When we can expect a new release with Django 2.0 support?

**Comment by ashwoods** [comment]
@wooyek this week.

**Comment by wooyek** [comment]
@ashwoods is there a new ETA?

**Comment by wyc902** [comment]
Is this issue resolved in django 2.0?

**Comment by ikosenn** [comment]
@wyc902 yes it is. version >=6.4.0

**Comment by ikosenn** [comment]
@wyc902 yes it is. version >=6.4.0

**Comment by Mee1ad** [comment]
django 2.2.3 
same error
AttributeError: 'URLResolver' object has no attribute '_regex'
