### ISSUE TITLE
A raven client "ignore_environment" parameter

### ISSUE THREAD

**Issue by azmeuk** [getsentry/raven-python#1137]
The same way the `Client` parameter `ignore_exceptions` ignores exceptions, it would be great to have a `ignore_environments` parameter that ignores everything. It would make it easier to use sentry in development or test environments, where we usually do not want it to report anything.

```python
env = "*******"
dsn = "*************"
try:
    1/0
except:
    raven.Client(dns=dsn, ignore_environments=["dev", "tests"], environment=env)
```
What do you think?

**Comment by ashwoods** [comment]
For raven 7.0 I'll be introducing disabling the client by passing None as dsn value.
