### ISSUE TITLE
Raven + Flask user_context ignored if using raise

### ISSUE THREAD

**Issue by reflash** [getsentry/raven-python#1146]
Hello,

I'm starting with Sentry to try it with my app, but I've faced an unexpected behaviour, at least from my point of view.
I've used the following code to verify that user context is correctly sent to my Sentry service app.

```python
def handle_text(message):
    user_id = message.chat.id
    name = message.from_user.first_name
    sentry.user_context({'id': int(user_id), 'username': name})
    raise SystemError("Sentry test exception")
```

The problem is that if I use `raise` keyword, I get no user_context on the Sentry side. But if instead, I raise some exception here, for example, NameError then the user context correctly appears on the Sentry side. What am I doing wrong? And is this an expected behaviour by design?

**Comment by mitsuhiko** [comment]
You mean `raise` as in reraise?

**Comment by reflash** [comment]
@mitsuhiko I expect the same behaviour for both, in this case I mean just raising an error

**Comment by mitsuhiko** [comment]
I still do not understand what you are actually attempting to do. `raise` does not "just raise an error". `raise` without arguments reraises the error on the stack.

**Comment by reflash** [comment]
@mitsuhiko I've provided code example, that's exactly the case

**Comment by mitsuhiko** [comment]
> The problem is that if I use raise keyword, I get no user_context on the Sentry side. But if instead, I raise some exception here, for example, NameError then the user context correctly appears on the Sentry side.

I do not undertand the question.

So `raise NameError('what')` works but `raise SystemError('what')` does not?

**Comment by reflash** [comment]
@mitsuhiko No, If I make an error in name or try access wrong dictionary key for example -> it works, if I explicitly use `raise` -> it doesn't.

**Comment by mitsuhiko** [comment]
I can't reproduce this. Do you have a minimal testcase?

**Comment by reflash** [comment]
I've found that the problem is actually caused by library wrapping Flask, so its not a problem in Raven
