### ISSUE TITLE
PySpark support

### ISSUE THREAD

**Issue by tedmiston** [getsentry/raven-python#1151]
I'm looking to integrate Sentry into a PySpark project.  Behind the scenes PySpark wraps and runs the Scala Spark code on the JVM.  This makes exception aggregation a bit more complicated vs pure Python code.

The Scala spark code uses log4j which I noticed Sentry's Java client supports.

I'm wondering if it'd be possible to use Sentry, the Python client, Java client, or something else to aggregate exceptions on PySpark code?

**Comment by tedmiston** [comment]
I found a corresponding PR on the Apache Spark repo to provide optional Sentry for the workers.

https://github.com/apache/spark/pull/17671/files

I guess I should add here that I'm trying to cover the spark driver as well as the workers.

**Comment by hangtwenty** [comment]
@tedmiston did you find a solution or workaround for this?

**Comment by AbhiPrasad** [comment]
We've released a PySpark integration as part of the [new python-sdk](https://github.com/getsentry/sentry-python): https://docs.sentry.io/platforms/python/pyspark/

New as of `sentry-sdk` version 0.13.0
