### ISSUE TITLE
Miracle in repo and pypi package

### ISSUE THREAD

**Issue by ziajka** [getsentry/raven-python#1166]
Hi Guys!

First of all, thanks for a great software.

Recently we're encouraging issue during our internal build. We found out that your pypi package contains one extra file.

Please unzip from here https://pypi.python.org/pypi/raven file `raven-6.4.0.tar.gz`. Inside you may find `raven/deprecation.py`

However when we take a look on repository this file doesn't exist:
https://github.com/getsentry/raven-python/tree/6.4.0/raven

I don't know exact reason however we're letting you know.

Cheers,
Dominik

**Comment by ashwoods** [comment]
Thx. :D Slipped in from another branch.

**Comment by bernalrs** [comment]
We also notice this while upgrading to version 6.4.0 and it is breaking our build as the file is incomplete and syntactically incorrect.

**Comment by thijstriemstra** [comment]
@ashwoods 

Same here, it's broken at the moment. Any news?

**Comment by ashwoods** [comment]
Finally gone. Thanks!
