### ISSUE TITLE
What is this comment in the code talking about?

### ISSUE THREAD

**Issue by thanatos** [getsentry/raven-python#1196]
[This passage in the code](https://github.com/getsentry/raven-python/blob/0c417999944646c0d8d27856f2440ecb6b1c336a/raven/breadcrumbs.py#L145-L155) reads as follows:

```python
        # We do not want to include exc_info as argument because it often
        # lies (set to a constant value like 1 or True) or even if it's a
        # tuple it will not be particularly useful for us as we cannot
        # process it anyways.
        kwargs.pop('exc_info', None)
        data.update({
            'message': formatted_msg,
            'category': logger.name,
            'level': logging.getLevelName(level).lower(),
            'data': kwargs,
        })
```

First,

> We do not want to include `exc_info` as argument because it often lies (set to a constant value like 1 or True)

`exc_info` is not "lying"; 1/`True` is a documented, valid value: it means to retrieve the exception information from `sys.exc_info`. See [`logging.debug`](https://docs.python.org/3/library/logging.html#logging.Logger.debug):

> If exc\_info does not evaluate as false, it causes exception information to be added to the logging message. If an exception tuple (in the format returned by `sys.exc_info()`) or an exception instance is provided, it is used; otherwise, `sys.exc_info()` is called to get the exception information.

The passage continues,

> or even if it's a tuple it will not be particularly useful for us as we cannot process it anyways

Why not? How does `sentry_client.captureException()` manage to capture the exception information, and why can't this code path use similar means?

We see a number of Sentry calls that end up originating from this area; they come from an incredibly generic area of our code unfortunately, so the exception information would be extremely useful in determining _what_ went wrong.

**Comment by dcramer** [comment]
@thanatos it'd be far too expensive to rebuild stacks for every single log message that would otherwise do it. If you have something that needs it, its usually an error, and bubbles up to a top level issue, rather than a supportive event.

@mitsuhiko can possibly comment on the comment, but I believe he's just saying "we can't serialize 'exc_info' here, and it being 1/True isnt useful to pass along".

**Comment by thanatos** [comment]
That explanation makes sense; the comment should be adjusted to just reflect that.
