### ISSUE TITLE
WSGI middleware - Display formatted tracebacks

### ISSUE THREAD

**Issue by azmeuk** [getsentry/raven-python#1212]
Hi. 
Sentry is very useful to catch production errors. Though at my company, we usually do not use it in the development phase, as we generate a lot of exceptions and prefer just see them on the fly instead of generating few valuable exception info in mass.

We would love raven to be able to format and display tracebacks like [cgitb](https://docs.python.org/3.8/library/cgitb.html) does. Maybe the piece of code that sentry server uses to format tracebacks is reusable ?
What do you think?

**Comment by dcramer** [comment]
It’s not reusable. This is best left up to other libraries.
