### ISSUE TITLE
Add blinker to requirements in documentation

### ISSUE THREAD

**Issue by jboegeholz** [getsentry/raven-python#1221]
After doing pip install raven --upgrade
and starting the flask app
the blinker module is missing.

Update of the documentation is needed.

**Comment by ashwoods** [comment]
Blinker is set as dependency of the flask integration, and the docs state you install raven for flask as `pip install raven[flask]`. @jboegeholz is that working for you?

**Comment by jboegeholz** [comment]
Thank You! I wasn't aware of the pip extras concept :-)
