### ISSUE TITLE
Drop python 3.3 support

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/raven-python#1241]
Currently, python 3.3 is broken in tox in our test suite with:

> DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.

Any reason not to just drop this from CI?

**Comment by ashwoods** [comment]
+1

**Comment by mitsuhiko** [comment]
Yeah. Let's kill it.

**Comment by ashwoods** [comment]
Dead.
