### ISSUE TITLE
How does this exception get sent without calling captureException?

### ISSUE THREAD

**Issue by sujaymansingh** [getsentry/raven-python#1266]
I have the following code

```py
from raven import Client

SENTRY_DSN = "..."

if __name__ == "__main__":
    Client(SENTRY_DSN)
    1 / 0
```

What happens is that the exception automatically gets sent to sentry (despite me not explicitly calling `captureException`)

This is pleasing for me, as I don't need to do much other than initialise the client in my `__main__` block (or a method it calls).

I was just wondering whether this is 'documented' behaviour, i.e. should I rely on this?

**Comment by ashwoods** [comment]
The sentry client installs a hook by default via [sys.excepthook](https://docs.python.org/3/library/sys.html#sys.excepthook)

**Comment by bfontaine** [comment]
Note: This is not related to Sentry per se, but be aware that [Python has a bug where `sys.excepthook` is not read correctly when using multithreaded programs](https://bugs.python.org/issue1230540). It was reported in 2005 and I can still reproduce it with Python 3.7 today.
I had an issue with a multithreaded program that wasn’t reporting exceptions to Sentry and I suspect this is why.
