### ISSUE TITLE
syntax error on python 3.7

### ISSUE THREAD

**Issue by AlecRosenbaum** [getsentry/raven-python#1277]
I'm getting this error on python 3.7 inside of docker. Using the python 3.6 image everything seems to be working fine.
```
    from raven.exceptions import InvalidGitRepository
  File "/usr/local/lib/python3.7/site-packages/raven/__init__.py", line 53, in <module>
    from raven.base import *  # NOQA
  File "/usr/local/lib/python3.7/site-packages/raven/base.py", line 691
    if transport.async:
                     ^
SyntaxError: invalid syntax
```

**Comment by mattrobenolt** [comment]
Ah, in 3.7 `async` is now a reserved word.

**Comment by birdbrained** [comment]
So will this be getting fixed?

**Comment by 01walid** [comment]
Any news on this? 
the docs claims the support of Python 3.7 though ..

**Comment by eli-schwartz** [comment]
It was fixed a year and a half ago in commit 67f4e89fbdaad42b7bf61b493a7b9d70d8e464b1, so why are you running a pre-6.x version?

**Comment by Juanlu001** [comment]
Perhaps this issue can be closed as such then?

**Comment by AlecRosenbaum** [comment]
I'm feeling pretty foolish now, @eli-schwartz is correct about it being fixed in 6.x. Looks like we have version 5.x pinned.

Guess it's time to update!
