### ISSUE TITLE
Support Django's sensitive data decorators

### ISSUE THREAD

**Issue by jaap3** [getsentry/raven-python#1281]
Django has some decorators that allow developers to annotate functions and methods with information about sensitive variables and post data: https://docs.djangoproject.com/en/2.0/howto/error-reporting/#filtering-error-reports

As far as I can tell the Django client from raven doesn't do anything with this information.

Processors are an alternative solution, but don't support granular control of when to filter something. i.e. key can be a safe var in one function, but highly sensitive in another one.

Is it possible to take these decorators into account? Would it be possible to write a filter that does so? Is it possible to somehow reuse the filter logic in [SafeExceptionReporterFilter](https://docs.djangoproject.com/en/2.0/howto/error-reporting/#custom-error-reports) 

I found an old PR (#345) that tries to support sensitive_post_params, but it got abandoned.

I'm willing to work on this, but I'm not familiar with the inner workings of Raven so hopefully someone can provide some guidance before I put some actual effort into this.

**Comment by untitaker** [comment]
I wanted the same thing and implemented https://github.com/untitaker/python-sensitive-variables instead.

(note: I am the author of the new Python SDK but the project I linked above is unaffiliated)
