### ISSUE TITLE
passing KeyError exception Failed

### ISSUE THREAD

**Issue by weinbergdavid** [getsentry/raven-python#1305]
I try to pass KeyError and it's fail due to 

> TypeError: 'KeyError' object is not subscriptable

this is my code:
`
    except KeyError as e:
        client.captureException(e)
`

And this is the error message:

Traceback (most recent call last):
....
  File "...\venv\lib\site-packages\raven\base.py", line 824, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "...\venv\lib\site-packages\raven\contrib\django\client.py", line 284, in capture
    exc_value = kwargs['exc_info'][1]
TypeError: 'KeyError' object is not subscriptable

it's failed in this row:
https://github.com/getsentry/raven-python/blob/4206873d63c461ffe6944029d36951514157928e/raven/contrib/django/client.py#L284
You need to wrap this line in try-except (than maybe you can try `exc.args[0]`).

Thanks, David.

**Comment by untitaker** [comment]
Hi @weinbergdavid, in your case you can call `captureException` without arguments and it should pick up the exception by itself.

`captureException` only accepts exc_info triples as returned by `sys.exc_info()`. This is fixed in the new SDK: https://docs.sentry.io/quickstart?platform=python

**Comment by weinbergdavid** [comment]
Thanks.
