### ISSUE TITLE
UWSGI + Nginx + Python (Flask) - ImportError: ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by FlamboyantOm** [getsentry/raven-python#1360]
I am using UWSGI + Nginx + Python (Flask)

When ever I fit page getting following **error** in log.

`*** no app loaded. going in full dynamic mode ***`

I have check with following command 

`sudo -u nobody python -c "from app.wsgi import application"`

Getting following **error** 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'app'
`

I have following folder structure :

/var/www/dashboard/web/app/app

Inside app i have  __init__.py file, which consist of code such :

from flask import Flask
from app.models import models
from app.controller import views

**Comment by untitaker** [comment]
Sorry, this has nothing to do with Sentry.
