### ISSUE TITLE
Does this project follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [getsentry/raven-python#1364]
Can i use this project with `~=` operator?
 
```
raven~=6.10.0
```

Does it follow [Semantic versioning](https://semver.org)?

**Comment by untitaker** [comment]
Yes, see changelog file

**Comment by untitaker** [comment]
sorry, that's raven-python. yes, it also follows semantic versioning, just like the new sdk

**Comment by alvassin** [comment]
thank you very much
