### ISSUE TITLE
When is the new version releasing?

### ISSUE THREAD

**Issue by yangjiel** [getsentry/raven-python#1366]
https://github.com/getsentry/raven-python/blob/d7d14f61b7fb425bcb15512f659626648c494f98/raven/utils/json.py#L58-L63

#1155 

I am experiencing the issue above and the master branch has fixed the issue. However, I use PYPI to install the Raven package, the latest version of that is 6.10.0 which the fixs haven't gotten applied yet.

I wonder when is it going to release the newer version? Raven hasn't released new tag for about 2 years.

**Comment by ashwoods** [comment]
raven isn't under active development anymore. It is encouraged to use the new sdk: https://github.com/getsentry/sentry-python
