### ISSUE TITLE
Passing exc_info=True when there is no exception seem to results in a gunicorn exception.

### ISSUE THREAD

**Issue by kitsunde** [getsentry/raven-python#176]
I did the mistake of putting in `exc_info` when I wanted to do regular logging:

```
def media_subscription(request):
    logger = logging.getLogger()
    logger.info('Media Subscription', exc_info=True, extra={'request': request})

    return HttpResponse("OK") # This gets returned.
```

But what I end up seeing in sentry is an error coming from gunicorn/socket:

> Stacktrace (most recent call last):
> 
>   File "gunicorn/workers/sync.py", line 33, in run
>    client, addr = self.socket.accept()
> 
>   File "python2.7/socket.py", line 200, in accept
>    sock, addr = self._sock.accept()

Exception:

> Types: error
> Types: [Errno 11] Resource temporarily unavailable

Curiously this didn't seem to happen when I used runserver on my OSX machine.

My dev machine (that worked):

```
Python 2.7.2
Django==1.4.1
raven==2.0.5
```

RedHat server (generated the above exception):

```
Python 2.7.0
Django==1.4.1
gunicorn==0.14.6
raven==2.0.5
```

**Comment by olgakogan** [comment]
still relevant

**Comment by xordoquy** [comment]
@olgakogan Can you provide the versions you are using when you had this issue ?
