### ISSUE TITLE
webapp2 support (e.g. Google App Engine)

### ISSUE THREAD

**Issue by cgallemore** [getsentry/raven-python#197]
I have the initial work done for the webapp2 support on GAE, I just need to get some documentation written for it and figure out how to write some unit tests for that.  Once I get that done, I'll submit a pull request.

**Comment by singpolyma** [comment]
Any progress here?

**Comment by xordoquy** [comment]
i don't think there vas been a PR for that yet.

**Comment by singpolyma** [comment]
Trying to extend the gist with support for sending raw POST body to sentry, but it always shows up in sentry as just ******** -- the word "password" isn't in it or anything, and it's not being filtered by a local processor... any ideas?

**Comment by singpolyma** [comment]
it's definitely being filtered based on content... if I just say "hai" in the POST body it works

**Comment by dcramer** [comment]
@singpolyma the server filters data based on various things as well: https://github.com/getsentry/sentry/blob/master/src/sentry/constants.py#L229
