### ISSUE TITLE
Tag Custom Data With captureException

### ISSUE THREAD

**Issue by jayakrishnag** [getsentry/raven-python#309]
Hi,

I want to capture an exception and tag it with my custom data. I used code below. I can see the exception on my console but could not find my tags. Am I missing something?

client.captureException(exc_info=error,
                                    debug_data={'app_id': '1000', 'package': 'data'})

Am using raven-3.3.6 and sentry sentry-5.4.5.

Thanks

**Comment by awesomehimanshu** [comment]
If i write this like as you said.

```
try:
 raise ValueError('Error in postgres function.')
except ValueError as err:
 client.captureException(exc_info=err,extra={'app_id': '1000', 'package': 'data'})   
```

It give error 

ERROR:  IndexError: tuple index out of range
CONTEXT:  Traceback (most recent call last):
  PL/Python function "ravenlog", line 7, in <module>
    client.captureException(exc_info=err,extra={'app_id': '1000', 'package': 'data'})
