### ISSUE TITLE
Raven behind the proxy

### ISSUE THREAD

**Issue by valdergallo** [getsentry/raven-python#338]
Hi, i need set proxy_handler in Raven's urllib.
Can I configure this on my django settings ?

**Comment by hamzdiou** [comment]
@valdergallo : Same issue, on ISS, environment seated by Python not working.
I found an other issue where Raven's sender was changed [(https://github.com/getsentry/raven-python/issues/1285)](url), have you done it directly on http.py ? If yes, is there an other way to do it ?

@xordoquy : Could be a pull request no ? Is there a code that will break if this upgrade is done ?

Thanks to all by advance
