### ISSUE TITLE
Turning off certificate verification

### ISSUE THREAD

**Issue by ulikoehler** [getsentry/raven-python#402]
I'm running sentry 6.4.2.1 on my VPS using nginx reverse proxy with a self-signed wildcard certificate. NGinx redirects all HTTP requests to HTTPS. My tornado application uses _SentryMixin_ from raven 3.6.1. to report errors to sentry.

However when an exception occurs or when capturing messages, I see this warning on the tornado CLI (exactly once per captured message/exception):

```
[W 131224 17:01:06 iostream:820] SSL Error on 17 ('46.38.237.81', 443): [Errno 1] _ssl.c:509: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

Is there any way I can turn of SSL certificate verification (or even use my self-signed CA for verification)? If not, is there any other encryption protocol that I can use?

Thanks in advance & Merry christmas!

**Comment by awong1900** [comment]
Good job.

**Comment by est** [comment]
related

> raven does not support SNI

https://github.com/getsentry/raven-python/issues/523
