### ISSUE TITLE
Processors can't sanitize/drop Cookie values

### ISSUE THREAD

**Issue by rcoup** [getsentry/raven-python#479]
Sentry seems to ignore the dict of values submitted in `data["sentry.interfaces.Http"]["cookies"]` in favour of reinterpreting `data["sentry.interfaces.Http"]["Headers"]["Cookie"]`, which means it's difficult to drop cookie values in a processor.

I feel like the code in [`SanitizePasswordsProcessor.filter_http()`](https://github.com/getsentry/raven-python/blob/master/raven/processors.py#L105) could probably be more nuanced around splitting on "=" - only do it for data/query_string, and process Cookie headers in a similar way? (obviously `=;` rather than `=&`)

Other option (we've gone with for now) is dropping Cookie from `headers` altogether if we already have a `cookies` dict.

**Comment by xordoquy** [comment]
Closing this thanks to the great job from @jbarbuto
