### ISSUE TITLE
"SyntaxError: invalid syntax" when installing master via pip

### ISSUE THREAD

**Issue by hheimbuerger** [getsentry/raven-python#496]
When installing the latest master (89024b4) via pip (`pip install -U git+https://github.com/getsentry/raven-python`) on Python 2.7, I'm getting a "SyntaxError: invalid syntax" for the following line: https://github.com/getsentry/raven-python/blob/master/raven/transport/aiohttp.py#L30

Looks reasonable, the asterisk really doesn't look like Python (2.x) syntax, or am I missing something?

**Comment by lkiss80** [comment]
When compiling raven, I see the SyntaxError tagged above, but the exit code for "python -m compileall" is still 1.  Shouldn't the exit code be 0 if this were truly not an issue?  This only came up when I ran a deployment, and my tool pays attention to the exit codes.

**Comment by mattrobenolt** [comment]
This isn't an issue, and exists in any library that tries to be python 2 and python 3 compatible in the same codebase. Similarly, this happens to gunicorn as well. The only fix we could do is to remove the python 3 specific syntax from our codebase, but I don't really think that's reasonable.

**Comment by xordoquy** [comment]
Upgrading your pip version might solve the issue.
I just tested a Raven install with Python 2.7 and pip 7.0.3, didn't saw a warning.

**Comment by mattrobenolt** [comment]
@xordoquy The underlying problem is from `python -m compileall`, which people run across their projects outside of pip. pip happens to call this internally and just masks the output so it's not surfaced to the user. So anyone who runs `python -m compileall` explicitly would be seeing this, which is a bit awkward.

**Comment by mattrobenolt** [comment]
And to clarify, `compileall` is naive to all of this. It just generates pyc files for every python file in the source tree, it doesn't actually import modules or anything, so it doesn't understand that certain files aren't even accessed based on conditional imports, etc.

**Comment by xordoquy** [comment]
Right, I assumed the compilall was part of the installation process.

**Comment by mattrobenolt** [comment]
Yeah, it totally is. pip just masks those errors by literally using a regular expression to parse them out. :) It's kinda gross. But it's not an error by any means, just noise.
