### ISSUE TITLE
How to disable sentry on development environment?

### ISSUE THREAD

**Issue by cabello** [getsentry/raven-python#538]
Hi, I am using raven 3.6.0 for production and test environments however I don't need it sending exceptions and messages from my local development environment, how can I disable it and prevent this message from appearing on my shell or every time I call `capture*`:

```
Raven is not configured (logging is disabled). Please see the documentation for more information.
```

**Comment by mo-mughrabi** [comment]
Hello, not quite sure how to disable it from the logging, currently in the development env this message keeps popping and as developer, would like to find a way to hide it since in console I don't have use for it. Any advise on how todo that? am on django 1.8 and python 2.7

**Comment by dcramer** [comment]
@mo-mughrabi we use the named logger 'raven' which can be configured using the standard logging package and tooling

**Comment by cabello** [comment]
Something like:
```python
if DEBUG:
    LOGGING['loggers']['raven'] = {
        'handlers': ['null'],
        'level': 'ERROR',
    }

**Comment by mo-mughrabi** [comment]
+1 @cabello thanks

**Comment by xarg** [comment]
I disabled the logging like so:

```
raven_logger = logging.getLogger('raven.base.Client')
raven_logger.setLevel(logging.CRITICAL)
```
