### ISSUE TITLE
Exception chaining

### ISSUE THREAD

**Issue by dwieeb** [getsentry/raven-python#550]
I would like to be able to have sentry display the original exception in the chain. In a lot of places we do something like this:

``` python
try:
    v = {}['a']
except KeyError as e:
    raise ValueError('failed') from e
```

I would like to be able to get at the KeyError in sentry just like the output of python when this code is ran:

```
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    v = {}['a']
KeyError: 'a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "t.py", line 4, in <module>
    raise ValueError('failed') from e
ValueError: failed
```

Is this possible in raven?

**Comment by dcramer** [comment]
@dwieeb its not today but I would +1 any work done towards this. We added support on the server for chained exceptions so it's probably not a lot of effort to add this to raven-python.

**Comment by dwieeb** [comment]
@dcramer I looked into this. Bad news. The python interpreter must do some magic to keep track of the KeyError in that example above. I am unable to get the `exc_info` from the original exception because python treats them as two different exceptions; that is, the exception info (including the tracebook) of the first has nothing to do with the exception info of the second.

It looks like we can't simply call `captureException` in the final `except` block.

```python
        try:
            raise ValueError('foo')
        except ValueError:
            # some kind of self.client call to record exc_info at this point in code
            try:
                raise TypeError('bar')
            except TypeError:
                self.client.captureException()
```

**Comment by dcramer** [comment]
Are you certain? The exception object has some special properties: __cause__ and __context__ (iirc)

I dont know a ton about Python and didn't try implementing it myself yet, but I thought we had enough info

**Comment by dwieeb** [comment]
Oh, in Python 3 there is an exception __context__, which contains a __traceback__. See https://docs.python.org/3/library/exceptions.html#built-in-exceptions. 

I assumed Python 3 isn't fully supported because some tests outright fail when running Python 3.

**Comment by dcramer** [comment]
@dwieeb it *should* be fully supported.

Python 2 definitely doesn't support chained exceptions, though we can provide helpers to fake it.

**Comment by dwieeb** [comment]
@dcramer https://github.com/dwieeb/raven-python/commit/f04ad91461fbd04e8c3824474a43de89f0d099fd

This may be a step in the right direction. Getting a weird test failure that I can't quite track down this second. I'll revisit this when I feel like digging in again. Any pointers would be appreciated.

```
DjangoClientTest.test_broken_500_handler_with_middleware 
tests/contrib/django/tests.py:279: in test_broken_500_handler_with_middleware
    assert exc['type'] == 'ValueError'
E   AssertionError: assert 'Exception' == 'ValueError'
E     - Exception
E     + ValueError
```

**Comment by xordoquy** [comment]
@dwieeb mind opening a PR ? It won't get merged yet but will makes it easier to review / test.

**Comment by kiwiholmberg** [comment]
Would very much like this functionality!

**Comment by albinekb** [comment]
Would very much like this functionality!

**Comment by cjerdonek** [comment]
In case it's of any help, Django added support for showing the exception chain in its "debug view" in Django 1.9. Here is the [changelog](https://docs.djangoproject.com/en/1.9/releases/1.9/#requests-and-responses), and here is the corresponding [ticket](https://code.djangoproject.com/ticket/23643). Maybe their code will be of help.

**Comment by cjerdonek** [comment]
> We added support on the server for chained exceptions so it's probably not a lot of effort to add this to raven-python.

@dcramer Can you point out where support on the server was added for chained exceptions (e.g. where in the code and/or relevant pull requests, commits, etc)? That might help with people wanting to take a look at this issue. Thanks!

**Comment by dcramer** [comment]
Take a look at the Exception interface docs:

https://docs.getsentry.com/hosted/clientdev/interfaces/

**Comment by cjerdonek** [comment]
@dcramer How would you like chained exceptions to be handled via the API? Should `sentry.interfaces.exception.Exception['values']` be a list containing more than one exception, or another way? [The "Failure Interfaces" section](https://docs.getsentry.com/hosted/clientdev/interfaces/#failure-interfaces) of the docs don't seem to mention chained exceptions explicitly.

The relevant raven-python code seems to be [here in `Exception.capture()`](https://github.com/getsentry/raven-python/blob/02aa7bee9addd1aaf2016af181c27a6ef9f37d01/raven/events.py#L73), where it returns an exception data dict, whose `"values"` list contains a single value.

**Comment by dcramer** [comment]
@cjerdonek sorry we need to improve those docs - 'values' is a list of exceptions, which is the chain. I do believe its inverted from the stacktrace order, and also not documented.

**Comment by cjerdonek** [comment]
Great, then it looks like adding support could be as simple as modifying [`Exception.capture()` here](https://github.com/getsentry/raven-python/blob/02aa7bee9addd1aaf2016af181c27a6ef9f37d01/raven/events.py#L59) to iterate over the exception chain, and returning a list of multiple values instead of a single value.

One can iterate over the chain by checking for a `__cause__` or `__context__` attribute on the exception (as you recalled above). This is documented / described in the "Enhanced Reporting" section of Python's [PEP 344](https://www.python.org/dev/peps/pep-0344/) ("Exception Chaining and Embedded Tracebacks").

**Comment by dcramer** [comment]
@cjerdonek yeah it shouldn't be overly difficult. It just needs to handle the python 2/3 case, and have some basic tests.

**Comment by cjerdonek** [comment]
I posted PR #811 for this.

**Comment by cjerdonek** [comment]
I just noticed this is still open. Since PR #811 was merged, I believe this issue can be closed now?
 Chained exceptions do show up in Sentry's web UI now.

**Comment by ashwoods** [comment]
@cjerdonek thx!

**Comment by phillbaker** [comment]
It looks like exception chaining is now the default behavior for the python client, in cases where we wrap exceptions to consolidate groups of exceptions, what's the recommended behavior?

Reading the code it seems like the following will work, however, we'll definitely lose some of the context around the exception:

```py
try:
    requests.get("http://example.com")
except requests.exceptions.ConnectionError as e:
     raise MylibError("Unable to connect", e) from None
```

**Comment by phillbaker** [comment]
Thanks @dcramer for taking a look.

Our issue is with the aggregation in hosted Sentry, I might be wrong, but it appears that exceptions are being aggregated by the original exception (from the xample above, requests.exceptions.ConnectionError), not the "grouped" exception (MylibError). 

Is this the best spot to continue the discussion or would a new issue be a better spot?

**Comment by cjerdonek** [comment]
I haven't noticed any issues with Sentry's aggregation of chained exceptions.

@phillbaker This is what you should be doing to take advantage of the client's support for chaining:

    try:
        requests.get("http://example.com")
    except requests.exceptions.ConnectionError:
         raise MylibError("Unable to connect")

That way Python chains the `ConnectionError` to `MylibError` (and Sentry will render it), and Sentry will aggregate only on the info you include in what you pass to `MylibError`'s constructor.

Doing `raise MylibError("Unable to connect", e) from None` breaks this because (1) including `from None` breaks the chain, and (2) includes the `ConnectionError` object in the constructor, which I could see causing Sentry not to aggregate different `MylibError` objects.

**Comment by chrisroat** [comment]
I'm not seeing this functionality in using `sentry_sdk` in a simple script with my `sentry.io` project.  Is it user error or was this functionality not ported to `sentry_sdk`?

**Comment by untitaker** [comment]
ref https://github.com/getsentry/sentry-python/issues/243
