### ISSUE TITLE
Update can silently diable error reporting from missconfigured servers due to failing ssl verification

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [getsentry/raven-python#554]
a miss-configured customer server actually failed to verify our ssl certificate,
so instead of sending the sentrys the errors where logged to stdout

a method to report such conditions without exposing the dsn key would be nice

(after all verify is supposed to prevent mitm attacks,
sending a unverified request to make verification failure known would expose the key anyway)

**Comment by xordoquy** [comment]
Up to now, I have always seen failure to send events logged.
Beside you have the manage.py raven test command to make sure it is properly configured.
Are you suggesting Raven could do more ?

**Comment by RonnyPfannschmidt** [comment]
failing ssl verification prevents sending the events to the sentry server
the main problem is that the recent version enables ssl verification by default,
which means that a broken base configuration suddenly causes event sending failures due to failing ssl verify

so a previously "working" installation stopped
it seems there is absolutely no mechanism in raven to report such conditions

**Comment by RonnyPfannschmidt** [comment]
as a extra bonus the manage.py raven test command exits as success even when sending the message fails

**Comment by xordoquy** [comment]
That one is a real issue.

**Comment by RonnyPfannschmidt** [comment]
```
(env):~/project-current> DJANGO_CONFIGURATION=Prod python manage.py raven test && echo did i fail
Client configuration:
  servers        : ['redacted']
  project        : 13
  public_key     : redacted
  secret_key     : redacted

Sending a test message... success!
Event ID was '7fd5cffc7d994d4cb95802493b0b173d'
ERROR 2015-01-23 13:28:55,567 base 13452 140447574755072 Unable to reach Sentry log server: <urlopen error [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed> (url: redacted)
Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/raven/transport/threaded.py", line 159, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File ".../lib/python2.7/site-packages/raven/transport/http.py", line 49, in send
    ca_certs=self.ca_certs,
  File ".../lib/python2.7/site-packages/raven/utils/http.py", line 62, in urlopen
    return opener.open(url, data, timeout)
  File ".../lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File ".../lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File ".../lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File ".../lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File ".../lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed>
ERROR 2015-01-23 13:28:55,569 base 13452 140447574755072 Failed to submit message: u'This is a test message generated using ``raven test``'
did i fail
```

**Comment by RonnyPfannschmidt** [comment]
well, even with that other bug, its still a fact that raven will cease to work if something breaks the ssl verification on the server - without direct notification, in the sentry

as a result we are practically unable to notice when a 3rd party breaks a server configuration after the fact

**Comment by xordoquy** [comment]
If your mail serveur changes its configuration and you have the Django's mail reporting system you won't get the errors.
If you need to make sure your system works you need to cron the raven test and make sure you get it every day or something like that.

**Comment by RonnyPfannschmidt** [comment]
well, this one happens on a sentry update too - if only external change triggered it i wouldn't consider it a sentry problem

**Comment by dcramer** [comment]
You unfortunately are going to have to rely on your logs if the remote server breaks. There's no reliable way to say "well the remote server seems broken, so lets notify the remote server that we saw it was broken".
