### ISSUE TITLE
Update to PyPI version?

### ISSUE THREAD

**Issue by allanjamesvestal** [getsentry/raven-python#559]
Hello,

It looks like the newest Raven version (v5.2.0) hasn't made the jump to [PyPI](https://pypi.python.org/pypi/raven/5.1.1) yet.

Would you be able to upload the newer version to the index? I'm using pip+git right now, but would much prefer a clean PyPI install.

Thanks for Sentry and Raven. They're life-savers (and the new versions/releases captured attribute is great to have).

**Comment by dcramer** [comment]
@allanjamesvestal is there a specific feature you need out of 5.2.0?

**Comment by xordoquy** [comment]
@dcramer mind if I build this package ?

**Comment by dcramer** [comment]
@xordoquy nope

**Comment by xordoquy** [comment]
There it is.
However, please note that the travis build for the tag has errored:
https://travis-ci.org/getsentry/raven-python/builds/50551004
