### ISSUE TITLE
Using raven.events.Message causes NotImplementedError

### ISSUE THREAD

**Issue by danielchao** [getsentry/raven-python#565]
The class Message in does not seem to have to_string() implemented

**Comment by xordoquy** [comment]
Do you have a bit more informations about when this might happen ?
It'll help making sure it's not dead code.

**Comment by danielchao** [comment]
Sure. I'm trying to send custom events by writing a new Handler class and following the example given in Client.capture(): 

        >>> capture('raven.events.Message', message='foo', data={
        >>>     'request': {
        >>>         'url': '...',
        >>>         'data': {},
        >>>         'query_string': '...',
        >>>         'method': 'POST',
        >>>     },
        >>>     'logger': 'logger.name',
        >>> }, extra={
        >>>     'key': 'value',
        >>> })

Errors out here in build_msg():

        if 'message' not in data:
            data['message'] = kwargs.get('message', handler.to_string(data))
