### ISSUE TITLE
Debian packaging 

### ISSUE THREAD

**Issue by arthurlogilab** [getsentry/raven-python#566]
... would be nice. 

Might contribute this at some point if no one else has worked on this.

**Comment by xordoquy** [comment]
Closing this as it is best discussed with Debian packaging teams.

**Comment by arthurlogilab** [comment]
Ok. I understand that you don't want some debian/ directory in your source tree. 

If anyone else needs debian packaging, we're successfully generating debian packages from https://github.com/arthurlogilab/raven-python/tree/debian

**Comment by dcramer** [comment]
You can also simply use fpm which is trivial to generate packages with
