### ISSUE TITLE
Distribute tests in the tgz

### ISSUE THREAD

**Issue by arthurlogilab** [getsentry/raven-python#567]
In the tgz distributed via pypi (I guess generated via python setup.py sdists) the tests are missing. In my humble opinion it's a good idea to ship the tests in the tgz aswell. 

Same thing goes for the docs subfolder, but I guess the answer can be different for the two cases. 

Is it deliberate to not ship these two sets of files ?

**Comment by xordoquy** [comment]
Actually the tests aren't shipped with the code as there is little to no reason a end user would use those tests rather than the git version.
What would the reason be we need to ship them ? Note that it'll make the package somewhat bigger and the installation longer.

**Comment by arthurlogilab** [comment]
I think it is quite common for python packages to ship with the tests so that one can run the tests before using the software. I haven't looked if there is a PEP that gives recommendations in that direction.

If I take the example of debian packaging, from a given tgz multiple packages can be generated, so you can split the files into "project", "project-tests", "project-docs", but for this to be possible the files have to be in the original tgz which is the reference. 

One other example : it is not uncommon for projects using make files to have "make tests" that run the tests so one can check it works before doing a "make install".

**Comment by xordoquy** [comment]
@arthurlogilab would it be ok for the packaging if we include the tests in the .tgz but we don't install it ?
