### ISSUE TITLE
Invalid Sentry DSN when using a public key

### ISSUE THREAD

**Issue by noplay** [getsentry/raven-python#569]
Hi,

Perhaps i do't correctly understand the notion of public DSN. When I try to use Sentry with public I got this exception:
```
    self._client = raven.Client(CrashReport.DSN, release=__version__)
  File "/site-packages/raven/base.py", line 139, in __init__
    self.set_dsn(dsn, **options)
  File "site-packages/raven/base.py", line 195, in set_dsn
    dsn_config = raven.load(dsn, transport_registry=self._registry)
  File "site-packages/raven/conf/__init__.py", line 54, in load
    scope_extras = transport_registry.compute_scope(url, scope)
  File "site-packages/raven/transport/registry.py", line 73, in compute_scope
    return transport.compute_scope(url, scope)
  File "python3.4/site-packages/raven/transport/base.py", line 57, in compute_scope
    raise ValueError('Invalid Sentry DSN: %r' % url.geturl())
ValueError: Invalid Sentry DSN: 'https://aaaaaaaaaaaaaaaaa@app.getsentry.com/38482'
```

* Is it an issue?
* Can we distribute a desktop application including sentry private key without security issue (i don't understand what are the exact access level of an API key)?

Thanks for the help

**Comment by dcramer** [comment]
Unless you're a browser-based implementation you should use the full DSN.

The security implication is only that someone can send events on your behalf, which your only resolve is to revoke the API key and ship a new one. There's no other access given by default with client keys.

**Comment by jamesgorrie** [comment]
Not wanting to reopen this - but have a question:

Could we not implement similar auth that we have in client JS to the server / app implementations?

Our use case is having an open source application and we are trying our best not to have secret config anywhere.

**Comment by dcramer** [comment]
There is no alternative that is secure. You just need to expose the secret and be willing to revoke it upon abuse.

**Comment by aviddiviner** [comment]
@dcramer I'd like to clarify this statement:

> The security implication is only that someone can send events on your behalf.

Does this mean that events can be sent only *to Sentry*, or that the API key can be used to make Sentry send events to somewhere else?

Thanks for your time.

**Comment by mattrobenolt** [comment]
It’s only for sending events into Sentry.

**Comment by cancan101** [comment]
I would also like to see the ability to use the public DSN with raven. I am deploying Python code to clients and would prefer to not have the full DSN in an untrusted environment. This would be conceptually the same as how I don't want the private DSN in the web bundle I send to users.

**Comment by dcramer** [comment]
Heads up we are removing the secret key (its already in progress) from all SDKs. There's not enough security provided by it, and given the nature of us supporting non-server-to-server communication these days its just not worth it.

**Comment by ermik** [comment]
If someone abuses the secret (whether it's the full DSN or the public version) — you have to revoke it. This will require all of the consumers to be updated. Common sense here, in terms of security, is that DSN **must** be disposable.

**Comment by ermik** [comment]
@dcramer ok, can we get a blog post on that? I don't fully understand the reasoning and I am very interested in the subject.

**Comment by dcramer** [comment]
@ermik it simply provides no additional security. You can have a DSN with only a public key, which is still very hard to brute force, and use that only for server-to-server communication. You can then generate a separate DSN to ship with client software, and as you mentioned, revoke when abused (or just block IPs using our tools).
