### ISSUE TITLE
Run the raven test SENTRY_DSN, message is sending.But the Sentry dashbroad is empty

### ISSUE THREAD

**Issue by fripSide** [getsentry/raven-python#571]
I deploy Sentry on Centos6.5 using mysql and redies. When I run raven test, it's show event is sending but the sentry message table is empty.The test message cannot be viewed at the sentry website.Here's the message.

(sentry)[root@surica sentry]# raven test http://93e5529224694425b70b70a07fbed934:b40887f3d0b24233819da0333454ac08@sentry.surica.cn/2
Using DSN configuration:
  http://93e5529224694425b70b70a07fbed934:b40887f3d0b24233819da0333454ac08@sentry.surica.cn/2

Client configuration:
  servers        : ['http://sentry.surica.cn/api/2/store/']
  project        : 2
  public_key     : 93e5529224694425b70b70a07fbed934
  secret_key     : b40887f3d0b24233819da0333454ac08

Sending a test message... success!
Event ID was '4bebe8081c2b4e44bde70d105b9beaaa'

**Comment by dcramer** [comment]
It's likely your workers aren't configured or there's some other kind of error.

```
sentry celery worker -B -l INFO
```
