### ISSUE TITLE
Raven and django-haystack not getting along

### ISSUE THREAD

**Issue by johnthedebs** [getsentry/raven-python#573]
I'm trying to use the latest versions of these libraries together (raven 5.2.0, django-haystack 2.3.1, django 1.7.5) and getting errors while using haystack's `rebuild_index` management command (it's wipes the index but fails to rebuild).

I found a workaround by modifying [this function](https://github.com/django-haystack/django-haystack/blob/master/haystack/utils/app_loading.py#L14) in django-haystack, but I'm not sure it's the best solution. The problem seems to be caused by the number of "."s in "    "raven.contrib.django.raven_compat".

**Comment by dcramer** [comment]
Would you be able to attach a traceback including the command you ran, just to help reproduction/understanding.

**Comment by johnthedebs** [comment]
https://gist.github.com/johnthedebs/6fe0960aa66b1773538b

**Comment by dcramer** [comment]
@johnthedebs thanks. I'm closing this as theres honestly nothing we can really do on our end as this is an issue w/ Haystack itself. (see the ref'd ticket for details)

**Comment by dcramer** [comment]
@johnthedebs could you confirm if you have 'raven.contrib.django.raven_compat' in INSTALLED_APPS, or if its 'raven.contrib.django' ?

**Comment by johnthedebs** [comment]
I have "raven.contrib.django.raven_compat" in my INSTALLED_APPS.
