### ISSUE TITLE
Zope contrib AttributeError getProperty on Anonymous users

### ISSUE THREAD

**Issue by puittenbroek** [getsentry/raven-python#579]
Currently the code here checks is user is None or not:

Which is good, but the 'getProperty' is not always available.
Plone/Zope has a 'Anonymous User",

    (Pdb) user
    <SpecialUser 'Anonymous User'>
    (Pdb) user.__class__
    <class 'AccessControl.users.SpecialUser'>
    (Pdb) user.__class__.__module__
    'AccessControl.users'
    (Pdb) user.getProperty
    *** AttributeError: getProperty

Looking at the code, best solution would be to check if the user obj is not an instance of AccessControl.users.SpecialUser.

**Comment by puittenbroek** [comment]
Or see if it has the getProperty via a hasattr. :)

**Comment by xordoquy** [comment]
It seems the link to the code isn't visible.

**Comment by puittenbroek** [comment]
https://github.com/getsentry/raven-python/blob/master/raven/contrib/zope/__init__.py#L98

**Comment by xordoquy** [comment]
sounds fair.

**Comment by puittenbroek** [comment]
Even better solution:

    from AccessControl.users import nobody # at top ofc
    if user is not None and user != nobody:

**Comment by puittenbroek** [comment]
I'll make a PR tomorrow :)

**Comment by xordoquy** [comment]
Perfect, looking forward to it :)

**Comment by dcramer** [comment]
Closing this as the PR was merged.
