### ISSUE TITLE
Logging from celery worker processes doesn't work under some circumstances

### ISSUE THREAD

**Issue by nailgun** [getsentry/raven-python#581]
This refers only to the **Threaded transport**.

I use Celery and Raven in my Django project. Project uses some third party libraries that are somewhat outdated and output warnings about some deprecations on initialization.

Also I have enabled WARNING level for sentry log hander.

This results in following failure scenario:

1. Celery worker starts (`celery worker -A myproject`)
2. Django initializes models and other stuff
3. Anything is being send into raven (in my case its deprecation warning, but it can be something more important)
4. Raven initializes threaded transport, which starts its thread.
5. ....
6. Celery forks worker processes
7. Worker processes adopt everything from parent celery worker, except threads.
8. Raven in worker process tries to send something to its thread, but the thread doesn't exist and message stays in the queue.

I have found a workaround for this: attach a handler to worker_init Celery's signal and reinitialize all transports there:

```py
from celery.signals import worker_process_init

@worker_process_init.connect
def reset_raven_transport_registry(sender, **kwargs):
    from raven.base import Client, TransportRegistry, default_transports
    Client._registry = TransportRegistry(transports=default_transports)
```

I don't know whose issue is it and I don't know would you fix it or not, I just want to add a solution if someone will encounter this problem, this will save a couple hours of debugging.

**Comment by kylec1** [comment]
Seems like this issue may have been fixed by https://github.com/getsentry/raven-python/commit/251a8728edc6f1365cfd3592c8bd63f976bfe7b4

**Comment by xordoquy** [comment]
Thanks for the feedback.
