### ISSUE TITLE
Remove ZeroRPC transport

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-python#586]
Let's assume that no one uses this if we dont get a response in a week or so, and then let's kill it off. The default examples suggest UDP (which wont work), and I imagine the use case is so small that even the remaining users of ZeroRPC may not even use Sentry.

**Comment by dcramer** [comment]
As a clarification, it's most likely this transport doesn't even work.

**Comment by xordoquy** [comment]
To be honest, let's remove it and handle it as 3rd party if someone really needs it.

**Comment by dcramer** [comment]
Closing this out as it was removed
