### ISSUE TITLE
Deprecate DSN-based transport configuration

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-python#587]
I want to move all implementations to a model where the transport is explicit instead of using the less understood DSN magic. This is to standardize things across languages where sometimes the schema based model doesn't make a lot of sense.

i.e.

```
Raven(dsn='...', transport=ThreadedTransport)
```

This also means we dont have to load all these modules in-memory and it's less confusing to end-users on how to use your own.

**Comment by dcramer** [comment]
I'm going to take care of this, starting with a refactor of how we manage DSNs.

**Comment by xordoquy** [comment]
Sounds sensible.

**Comment by kainz** [comment]
What about users of the SENTRY_DSN environment variable for environment-based configuration management?

**Comment by dcramer** [comment]
@kainz you cant configure most of the clients with just the environment, and that's intended for sensitive things less so than "heres how my app works"

**Comment by dcramer** [comment]
Work is being done in dsn-refactor branch.

I have a few goals with this branch and intend to rebase+force-push, so everyone should avoid touching it.
