### ISSUE TITLE
Post Body "<unavailable>" when error happens in Django Rest Framework view

### ISSUE THREAD

**Issue by jhgg** [getsentry/raven-python#591]
Title explains it. Looks like raven doesn't send over the post body when an error happens in a DJRF view/viewset. The content-type of the body is application/json.

**Comment by xordoquy** [comment]
A test case would really help here.

**Comment by mochawich** [comment]
I'm having the same issue when sending a POST request with json body to Django that uses DRF.
If any exception happens inside a DRF view, sentry log will show:
```
Request
URL:	......
Method:	POST
Body:	<unavailable>
```

**Comment by xordoquy** [comment]
Reproduced.

**Comment by kutenai** [comment]
Any chance of a solution? This would be awfully helpful right now..

**Comment by dcramer** [comment]
I'm not actually sure if we can reliably get this. The only generic solution I see is having Raven always overload the POST handler and capture it. That's fairly complex for streaming requests as it effectively means we have to create a temporary buffer.

Alternatively, we could assist with a solution to support this with DRF.

Either way, for clarity this is mostly likely the responsibility of DRF as it's somehow killing the body.

**Comment by xordoquy** [comment]
As maintainer of both project, i second the responsability being on drf at this stage. I'm lacking time to to further on this

**Comment by pbassut** [comment]
+1

**Comment by fernandogrd** [comment]
@xordoquy should we open a issue on DRF project?

As far as I could understand, DRF defines a new request object, without body attribute:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L122

And raven tries by default django's body, raw_post_data or request.POST

Is that correct?

**Comment by khazidhea** [comment]
Any updates on this?

**Comment by tomchristie** [comment]
There is no obvious way to resolve this. REST framework parsers read the request.stream, and the data is then not subsequently available.

Feasible that 'request.data' might end up being a supported interface in Django core, at which point sentry could use that to make the *parsed* data visible.

**Comment by tkazec** [comment]
Given DRF's popularity, at this point wouldn't a DRF-specific fix be in order?
