### ISSUE TITLE
Incompatible with django-haystack

### ISSUE THREAD

**Issue by chriskief** [getsentry/raven-python#592]
After upgrading to raven==5.2.0, I'm encountering the following error:

```python
File "/lib/python2.7/site-packages/haystack/utils/app_loading.py", line 22, in is_app_or_model
    raise ImproperlyConfigured("'%s' isn't recognized as an app (<app_label>) or model (<app_label>.<model_name>)." % label)
django.core.exceptions.ImproperlyConfigured: 'raven.contrib.django' isn't recognized as an app (<app_label>) or model (<app_label>.<model_name>).
```

This is due to the label value in apps.py containing periods:

```python
class RavenConfig(AppConfig):
    name = 'raven.contrib.django'
    label = 'raven.contrib.django'
    verbose_name = 'Raven'
```

Haystack uses the following to determine whether something is an app or model (haystack/utils/app_loading.py):

```python
def is_app_or_model(label):
    label_bits = label.split('.')

    if len(label_bits) == 1:
        return APP
    elif len(label_bits) == 2:
        return MODEL
    else:
        raise ImproperlyConfigured("'%s' isn't recognized as an app (<app_label>) or model (<app_label>.<model_name>)." % label)
```

Because of the periods, len(label_bits) returns 3 causing the error to be raised.

If the periods are removed in the label, the error goes away:

```python
class RavenConfig(AppConfig):
    name = 'raven.contrib.django'
    label = 'raven_contrib_django'
    verbose_name = 'Raven'
```

**Comment by xordoquy** [comment]
You should use `raven.contrib.django.raven_compat`. The issue isn't just with haystack but with django that'll use the the last part of the path as the application name and this will conflict with other applications.
