### ISSUE TITLE
Incompatible with django-haystack

### ISSUE THREAD

**Issue by chriskief** [getsentry/raven-python#594]
Apologies for re-opening this issue but you have misunderstood the error message and mistakenly closed the bug (https://github.com/getsentry/raven-python/issues/592).

Here are the settings that I am using:

```python
INSTALLED_APPS = (
...
'raven.contrib.django.raven_compat',
...
)
```

As you can see, the proper package is being used.

```python
File "/lib/python2.7/site-packages/haystack/utils/app_loading.py", line 22, in is_app_or_model
    raise ImproperlyConfigured("'%s' isn't recognized as an app (<app_label>) or model (<app_label>.<model_name>)." % label)
django.core.exceptions.ImproperlyConfigured: 'raven.contrib.django' isn't recognized as an app (<app_label>) or model (<app_label>.<model_name>).
```

The error message references ```raven.contrib.django``` because that is the label name being used in raven/contrib/django/apps.py (https://github.com/getsentry/raven-python/blob/master/raven/contrib/django/apps.py) which was introduced as of raven==5.2.0:

```python
class RavenConfig(AppConfig):
    name = 'raven.contrib.django'
    label = 'raven.contrib.django'
    verbose_name = 'Raven'
```

As explained in the original bug, the label name uses periods which conflicts with the following Haystack code:

```python
def is_app_or_model(label):
    label_bits = label.split('.')

    if len(label_bits) == 1:
        return APP
    elif len(label_bits) == 2:
        return MODEL
    else:
        raise ImproperlyConfigured("'%s' isn't recognized as an app (<app_label>) or model (<app_label>.<model_name>)." % label)
```

The fix is to not use periods for the label value:

```python
class RavenConfig(AppConfig):
    name = 'raven.contrib.django'
    label = 'raven_contrib_django'
    verbose_name = 'Raven'
```

**Comment by xordoquy** [comment]
No need to apologize here, I'm sorry I closed the previous issue too fast. Indeed it's a different issue form the one I thought.
