### ISSUE TITLE
Is there a way to manually pass in user_context?

### ISSUE THREAD

**Issue by ryanio** [getsentry/raven-python#600]
I'm not using Flask-Login but I'd like to manually pass in some information for user_context, would this be possible?

[Here is where it's being set in raven/contrib/flask.py](https://github.com/getsentry/raven-python/blob/2818cb00381d77f839458620c2ac1c9125dfd237/raven/contrib/flask.py#L192)

**Comment by dcramer** [comment]
While it seems we dont (and should) expose the methods on the Sentry() wrapper, you can just call Sentry().client.user_context()

**Comment by ryanio** [comment]
Okay thanks! Do you by any chance have a 1 liner example of how to get the
context of Sentry() to pass user_context? If possible I'd like to do it in
one of my auth methods in my User model

**Comment by dcramer** [comment]
@ryanio 

sentry = Sentry(app)

@app.before_request
def bind_user_context():
    sentry.client.user_context(...)

**Comment by ryanio** [comment]
Awesome that makes a lot of sense, thanks!
