### ISSUE TITLE
Report Python version number.

### ISSUE THREAD

**Issue by fletom** [getsentry/raven-python#602]
I requested this feature in Sentry support and @mitsuhiko asked me to report it here. It seems very weird to me that the Python Sentry client reports the version numbers of packages but not the version number of Python itself. Surely this is important information when debugging errors, and is probably fairly simple to add?

**Comment by xordoquy** [comment]
@fletom The reason is simple, it's easy to mess with the packages versions but not so much with the Python.
This being said this does make sense.

**Comment by fletom** [comment]
Sweet, thanks!
