### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by chrisspen** [getsentry/raven-python#607]
The current raven package is uninstallable from pip in Python 2.7:

     $ pip install raven
    ....
      File "/home/chris/git/myproject/.env/lib/python2.7/site-packages/raven/transport/aiohttp.py", line 31
        def __init__(self, parsed_url, *, verify_ssl=True, resolve=True,
                                        ^
    SyntaxError: invalid syntax

**Comment by xordoquy** [comment]
It is an error during compilation for a transport you won't be able to use anyway (Python 2.x). It doesn't affect the installation.
