### ISSUE TITLE
A compatibility table about raven and sentry server is needed

### ISSUE THREAD

**Issue by reorx** [getsentry/raven-python#611]
As far as I know:

- raven 5.3.1 is incompatible with Sentry 6.4.4 (this was encountered by me today)
- raven 5.0.0 is incompatible with Sentry 6.3.3 (reported in #467 )

It very confusing that the protocol in major version of both client and server are not compatible with each other, which is not very friendly to the users. Many company has been using sentry for a long time, old ravens lives in their legacy projects, upgrade them to the latest version is hard enough, let along trying to make out which version of raven should be used for their 6.x Sentry server.

Since raven is already not backward compatible, a table to tell which version of raven works with which version of Sentry is needed, to make life easier for us.

**Comment by dcramer** [comment]
We don't change protocols much, and Sentry 6.4 is about a year and a half old.

While I agree it might be a useful thing, the truth of it is we dont support old versions of the server, and we generally list in the changelog when protocols update.

PR's welcome though.

**Comment by Velmont** [comment]
This is super confusing. I'm getting this about protocol (6).

I don't control the Sentry server, and I have no idea what version I should use.  Maybe someone knows what 6.4.4 needs?  Maybe 6.4.4 is in Debian since so many seem to be using it?

**Comment by dcramer** [comment]
We dont release anything to apt, so nothing should be in repositories.

I agree a compatibility table would be a good addition, and should be fairly easy to build from the CHANGES file (at least recent version).

**Comment by luiscvalmeida** [comment]
Agreed, just had the same problem. I have the Sentry v6.4.4 and just tried to run the test command with Raven v5.7.2 and didn't work (protocol problem). I'm now trying to find the most recent raven version to work with this sentry version.

**Comment by pztrick** [comment]
I just had a failed upgrade from 7.0.0-dev to 8.4 (performing `sentry upgrade`) and was forced to roll-back to 7.0.0. I am just trying to add one more project, which with a fresh `pip install raven` was too new of a client to communicate with v7 ... so this kind of table would be useful also as I would prefer to use newest client also compatible with v7.

I think troubleshooting the upgrade to v8 would be too tedious right now. ;)
