### ISSUE TITLE
Break aiohttp out into its own package

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-python#618]
https://github.com/getsentry/raven-python/issues?utf8=%E2%9C%93&q=is%3Aissue+aiohttp

^^ this points out the obvious problem that will forever exist otherwise

**Comment by mattrobenolt** [comment]
To point it out, there are 2 syntax issues. The variadic `*` which is what's visible in the SyntaxError. But even if we remove that (since we don't need this for python 3), we next hit `yield from` which only exists in python 3. :(

**Comment by dcramer** [comment]
https://github.com/getsentry/raven-aiohttp

**Comment by dcramer** [comment]
304faee8b1a986deceb7d64084c4df5df45a51e8 removes aiohttp from core

**Comment by dcramer** [comment]
This will be fixed in 5.4.0

**Comment by kengruven** [comment]
Wow.  That might be the fastest I've ever seen a bug get fixed!  I applaud your speed and diligence.  You've definitely earned a fan here today.

**Comment by kengruven** [comment]
I hate to re-open this, but it looks like there's a problem with the wheel.  I'm still seeing the error when I install raven 5.4.0 with pip.

From <https://pypi.python.org/pypi/raven/5.4.0>, the wheel's URL is <https://pypi.python.org/packages/py2.py3/r/raven/raven-5.4.0-py2.py3-none-any.whl#md5=c356efa854cc1e7ac4c06e886d309aad>.  I downloaded that, renamed it to .zip, unpacked it, and raven/transport/aiohttp.py is still there.

**Comment by mattrobenolt** [comment]
Hmm, wtf. Lemme see what's happening, and if I messed up, I'll cut a 5.4.1 to fix it.

**Comment by mattrobenolt** [comment]
And if pypi wasn't down right now... :(

**Comment by mattrobenolt** [comment]
Hmm, Yeah, so when creating the wheel locally... I get the `aiohttp.py`, but it doesn't exist in a normal `sdist` build, and isn't in my source tree.

I'll figure this out and cut a new version soon.

**Comment by mattrobenolt** [comment]
@kengruven Alright, I pushed a 5.4.1, and manually verified it before uploading the packages. No `aiohttp.py` in these. Sorry about that and thanks for letting me know!
