### ISSUE TITLE
Improve documentation about transports

### ISSUE THREAD

**Issue by kengruven** [getsentry/raven-python#621]
I ran into a lot of trouble with this, so I'm sure other people must have, too.  I can't tell if it's a documentation problem, or a code problem, or both.  I was able to fix my setup with just changes to my code and configuration, though.

Background: I need to use a synchronous transport (because my application's process will exit shortly after an exception that I want to report to Sentry), so when I heard that Sentry used an async transport by default, I went and read this document: http://raven.readthedocs.org/en/latest/transports/index.html

First of all, the sentence "By default, Raven uses a threaded asynchronous transport, but you can easily adjust this by modifying your SENTRY_DSN value." is a little confusing.  It makes it sound like the DSN is what selects the transport.  But then two lines down when it shows some sample code, the DSN doesn't say what transport to use.  The "transport=" keyword parameter does.  But maybe the strange wording here was intentional.  I'll come back to this below.

When I try something like this:

    import raven
    s = raven.Client(dsn='https://FOO:BAR@app.getsentry.com/BAZ',
                     transport=raven.transport.HTTPTransport)
    try:
        1/0
    except:
        s.captureException()

it doesn't show up in the Sentry dashboard.  Similarly for raver.transport.RequestsHTTPTransport.  (It returns an event_id without error, but after a bit of searching I discovered that the event_id is created on the client-side, so this was not an indication of success.)

Upon digging through the logs, I discovered that it was failing here: https://github.com/getsentry/raven-python/blob/master/raven/transport/base.py#L29

It turns out that each Transport class has its own "scheme" list, and it will refuse to even try to send an event unless your store_endpoint has a protocol in that list.  ThreadedHTTPTransport (the default) has ['http', 'https', 'threaded+http', 'threaded+https'].  HTTPTransport's is ['sync+http', 'sync+https'], and RequestsHTTPTransport's is ['requests+http', 'requests+https'].  Internally, it builds the store_endpoint from the DSN you provide, with the same protocol.

This, combined with the strange sentence at the top (which suggested that the DSN needed modification in order to pick a different Transport) led me to figure out how to get it working with other transports.  For example, to use the RequestsHTTPTransport, I had to:

 1. pass transport=raven.transport.RequestsHTTPTransport to the Client initializer, and also
 2. change my DSN from "https" (as getsentry.com had told me) to "requests+https".

Then everything works!  But this was not at all easy to figure out.

By the way, this also means that the sample code on page <http://raven.readthedocs.org/en/latest/transports/index.html> won't work.  It asks for transport=HTTPTransport, but the DSN URL starts with "http", when it should start with "sync+http".

Alternatively, I suppose, you could just remove check_scheme.  I'm not sure why it exists.

**Comment by dcramer** [comment]
It looks like I overlooked this somehow during the refator. Thanks for digging into this.

I will work on getting some tests to cover this as well as fix the schema issue.

**Comment by svenstaro** [comment]
Why would one need to use a new DSN as well as specify the transport? This doesn't really make sense to me. If you need to do both, how is that better than specifying the transport as part of the DSN only?

**Comment by dcramer** [comment]
@svenstaro we deprecated the schema-based DSN configuration, but we missed an issue where it was still being required

**Comment by svenstaro** [comment]
Ok so then this isn't merely a documentation bug as this issue claims but a functionality issue, just so I understand the issue?

**Comment by dcramer** [comment]
Yep. That's correct. Hoping to have time today to take a look at this.

**Comment by dcramer** [comment]
I've fixed the scheme parsing issues in d3623e897de6be30da7fab2a1fff571be254edec and this will go out in the next release (once we confirm stability)
