### ISSUE TITLE
Strange behaviour while running Django management command

### ISSUE THREAD

**Issue by playpauseandstop** [getsentry/raven-python#626]
I ran into very strange problem, when on raising exception from the custom management command it being accessible in the Sentry, but in same time producing next traceback in the console,

```
Traceback (most recent call last):
  File "./<project>/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/<project>/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/<project>/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/<project>/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/<project>/venv/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 49, in new_execute
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

I cannot understand how it possible to happen, as exception clearly catched and should be reraised instead of producing another one exc. 

Can you point me out and help to understand what's going on?

----

raven: 5.4.2
Python: 2.7.6
OS: Ubuntu 14.04.2
Host: DigitalOcean

**Comment by playpauseandstop** [comment]
And the most strangest part, that using Python 2.7.10 with pyenv fixes the problem and exception properly shown in console without producing traceback.

Any ideas? Only way to fix is using Python 2.7.10?

**Comment by dcramer** [comment]
This sounds like something caused the exception to disappear from the env. The syntax and behavior should be correct, and I can't really explain why it would happen.

**Comment by playpauseandstop** [comment]
Okay, I got your point, just in case of curiosity I fixed this by changing current behaviour to using,

```python
        except Exception as err:
            from raven.contrib.django.models import client
            from raven.utils import six

            client.captureException(extra={
                'argv': sys.argv
            })
            six.reraise(err, None, sys.exc_info()[2])
```

It's not ideal solution, but somehow it works in my case
