### ISSUE TITLE
install_sys_hook (on by default) breaks older code

### ISSUE THREAD

**Issue by vmalloc** [getsentry/raven-python#634]
Our code uses multiple sentry clients for different projects in different modules. The introduction of the install_sys_hook in v5.5.0 breaks such projects, because the first client to be initialized captures exceptions from everywhere because of the sys.excepthook hook... I strongly feel this should be an opt-in parameter, not opt-out...

**Comment by dcramer** [comment]
@vmalloc that would go against the rest of our configuration which is all opt-out (i.e. you install it with your framework and we inject a bunch of things)

I think the case of using multiple clients isn't super common, though I definitely understand the pain of dealing w/ this after the fact.

Just to keep things orderly, I'm going to close this as wontfix. We might want to improve logging and documentation around it, but I think opt-in for crash reporting is too complex as people dont know which levers to pull.
