### ISSUE TITLE
Sentry in Flask hangs on start

### ISSUE THREAD

**Issue by pavel-francirek** [getsentry/raven-python#643]
Hello,

my Flask application hangs in debug mode start (python /www/bin/main.py) with no error message. 

Strace shows:

.....
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9962864a10) = 11689
.....
wait4(11689, 

Web starts again if I comment out inicialization:
sentry = Sentry(app, logging=True, level=logging.ERROR)

SENTRY_DSN is set in config file.

But it works on another server. "raven test" works on both.
Library version is:
dev:/www/$ pip list | grep raven
raven (5.5.0)

I was unable to find other differences between both virtual servers but I can try if you tell me what dependencies are required for client library start.

Thank you
Pavel

**Comment by dcramer** [comment]
By default we launch a thread in the background. You can change to the synchronous transport, but generally it shouldn't affect things.

Unfortunately, beyond that I'm not sure how we can help as it seems like a very use-case specific problem.
