### ISSUE TITLE
Flask extension broken for Flask-Login 0.3.0

### ISSUE THREAD

**Issue by boydgreenfield** [getsentry/raven-python#655]
Specifically the [following line](https://github.com/getsentry/raven-python/blob/master/raven/contrib/flask.py#L152) in the extension will raise a TypeError:

`is_authenticated = current_user.is_authenticated()`

Switching to:

``is_authenticated = current_user.is_authenticated`

as well as two other `.is_anonymous()` calls, resolves the problem.

**Comment by boydgreenfield** [comment]
Ohp, thanks @dcramer! – was just pulling things together for a PR but looks like you have it. 

Note here is the relevant changelog for Flask-Login: https://github.com/maxcountryman/flask-login/blob/93a5e20ba7289c3c0ed440faaa5b195d36f392cb/CHANGES

**Comment by dcramer** [comment]
Fixed in latest release
