### ISSUE TITLE
Using git to determine the release fails in Django integration

### ISSUE THREAD

**Issue by renatooliveira** [getsentry/raven-python#657]
When adding the RAVEN_CONFIG to django settings.py, I had to add a '..' to the path to get the root of the git repository.

With the current instructions it says that the settings.py folder is not the root of a git repository

```
raven.exceptions.InvalidGitRepository: /path/to/settings/ does not seem to be the root of a git repository
```

**Comment by dcramer** [comment]
@renatooliveira can you paste config on how you do it?

**Comment by renatooliveira** [comment]
sure, 

```
RAVEN_CONFIG = {
    'dsn': 'https://sentry_stuff',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    'release': raven.fetch_git_sha(os.path.join(os.path.dirname(__file__), '..')),
}

**Comment by dcramer** [comment]
Try doing os.path.normpath() around that as it might be keeping it a relative path

**Comment by renatooliveira** [comment]
With the original config? The one that I pasted works.

**Comment by dcramer** [comment]
Ah! Are you just talking about our basic config? It's kind of intended that you have to figure out the path since repos vary (i.e. ours is ../..)

**Comment by renatooliveira** [comment]
Yes, got that. I was setting up the project quickly and didn't pay attention on this. But since the path always vary, doesn't seem to me that the path would ever be the settings.py folder. Maybe putting the default path one level above and saying in the docs that it could vary from project to project would be better for new users?
