### ISSUE TITLE
Minor py3 compatability issues

### ISSUE THREAD

**Issue by lukasjuhrich** [getsentry/raven-python#659]
In a few locations, instead of using the `six` utilities, incompatible syntax has been used.

Known issues to me:
- usage of `xrange`
- usage of `unicode`

Pull request follows.

@dcramer please consider testing raven-python with python3 as well. I could easily get the tests running using a virtualenv.

Also, please note that I had to fork your repository in order to port my package to py3.

**Comment by dcramer** [comment]
@lukasjuhrich will get a bugfix release out -- we incorrectly ignored some failing builds (due to some false reds)

**Comment by dcramer** [comment]
Few more changes had to be made and should be good as 5.7.1.

Sorry about that!

**Comment by lukasjuhrich** [comment]
Thanks a lot, everything works as expected!
