### ISSUE TITLE
Add support for custom CA_BUNDLE

### ISSUE THREAD

**Issue by alexandrul** [getsentry/raven-python#665]
During development it would be pretty useful to use a custom CA_BUNDLE.

I would check for a RAVEN_CA_BUNDLE env var as the last step in conf/defaults.py, a pull request should be submitted by the end of the day, unless someone else has a better idea.

**Comment by mattrobenolt** [comment]
Hey @alexandrul, you should already be able to do this by adding `?ca_certs=...` to your DSN.

So something like: `SENTRY_DSN = https://....@example.com/1?ca_certs=/path/to/certs.pem`

This is documented at: https://docs.getsentry.com/hosted/clients/python/transports/#transports
