### ISSUE TITLE
Obsolete advice related to gunicorn

### ISSUE THREAD

**Issue by aaugustin** [getsentry/raven-python#666]
https://github.com/getsentry/raven-python/blame/master/docs/integrations/django.rst#L301-L312 suggests running the `validate` management command when gunicorn starts.

It's hard to tell the underlying reasoning for sure because the commit message doesn't provide any explanation and doesn't reference a ticket but I believe the intent is to trigger the app-loading process before beginning to handle the first request.

In Django 1.7+ this isn't useful anymore because the app-loading process was refactored. As of tomorrow Django 1.7 will be the oldest supported version. I suggest to remove this paragraph from the documentation.

If there's a reason why this still matters, it would be nice to give some hints. Otherwise it just confuses people who have trouble confirming that their Sentry install works and it encourages cargo-cult setup.

**Comment by dcramer** [comment]
I am very happy this issue is #666

**Comment by aaugustin** [comment]
I also enjoyed the issue number and celebrated it with the appropriate Iron Maiden song ;-)
