### ISSUE TITLE
Python3 with 5.8.0 InvalidDsn exception

### ISSUE THREAD

**Issue by jofusa** [getsentry/raven-python#674]
I haven't dug into this to much. Downgraded to 5.7.2 and it's working. It looks like that the DSN is being converted to bytes and failing the DSN check.

```python
client = raven.Client(dsn=settings.SENTRY_DSN)

raven.exceptions.InvalidDsn: Unsupported Sentry DSN scheme: b'https' (b'https://XXXXXX@app.getsentry.com/43995')
```

**Comment by dcramer** [comment]
Def need to get our test suite in order so we stop ignoring red builds. Gonna start killing tests that arent consistent.
