### ISSUE TITLE
certain exceptions at serialization seem to prevent sending messages to the server

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [getsentry/raven-python#682]
given the following code both raven 5.1.1 as well as the latest pypi version (5.8.1 at the time of writing) will no longer send a message to the server

``` python
"""
contrived example, simply the first variant that broke sending a sentry message for me

"""

import raven

client = raven.Client(dsn='<dsn>')

class BreakMe:
    def __getattr__(self, name):
      raise BreakMe, name


def fun():

    breakme = BreakMe()

    raise ValueError, breakme


try:
    fun()
except:
    client.captureException()

```

**Comment by RonnyPfannschmidt** [comment]
while that code looks quite horrible, its what will happen when one has to deal with suds,

and it can happen in a slightly different fashion when dealing with sqlalchemy mapped instances in the expired /detached state

unfortunately making suds reasonable is practically impossible

**Comment by mitsuhiko** [comment]
Given the code you just provided I cannot reproduce this on `master`.  It sent it just fine.  What version of Python and which interpreter are you using?

**Comment by RonnyPfannschmidt** [comment]
The interpreter in question is one of the 2.7 series

I can collect more info next week back at work

**Comment by RonnyPfannschmidt** [comment]
closing as cant reproduce and api is deprecated
