### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED with ?ssl_verify=0

### ISSUE THREAD

**Issue by mikemhenry** [getsentry/raven-python#683]
I might not understand if the ?verify_ssl=0 param appended to the DSN URL is supposed to skip the SSL verification by the project to the Sentry server or the Sentry server to the project. 

What is the correct way to use a self-signed certificate on the Sentry server? I'm hosting my own Sentry server on a ubuntu vps.

Thanks,
Mike

**Comment by mitsuhiko** [comment]
Instead of disabling SSL you should instruct raven to use the certificate of your server.  You can specify `ca_certs` and point it to a certificate bundle. Disabling SSL verification is not the way to go.

**Comment by mitsuhiko** [comment]
I will verify though that `verify_ssl=0` works.

**Comment by mitsuhiko** [comment]
Looking over it not all transports support disabling this. Are you using a specific transport?

**Comment by mikemhenry** [comment]
I'm using ThreadedHTTPTransport. I've got the output of `python manage.py raven test` handy if you need anything from that. I'll look into using the `ca_certs` bundle method. I know that's the right way to do it but I was thinking that for a one off/benchmarking thing this would be okay.

**Comment by mitsuhiko** [comment]
I will make sure we support this for the popular transports.

**Comment by lsde** [comment]
+1
ThreadedHTTPTransport is default for Flask integration which therefore doesn't have ability to disable SSL verification at the moment.

**Comment by dcramer** [comment]
I have confirmed that ?verify_ssl=0 on the DSN *does* disable SSL verification. Has anyone come up with a case that its not true?

**Comment by mikemhenry** [comment]
Which transport(s) have you tested?

**Comment by dcramer** [comment]
Sorry, I meant specifically with Threaded, which simply inherits form HTTP. I know the 'requests' transport does not support all options, but the Threaded/Sync transports are the basis for the describe options.

**Comment by mikemhenry** [comment]
I don't have time to test this right now but I'm going to mark it closed and if I have an issue you with it (or anyone else does) they can re-open the issue. Thanks for looking into it!

**Comment by danieldai** [comment]
Should it be verify_ssl=0?

**Comment by est** [comment]
related

> raven does not support SNI

https://github.com/getsentry/raven-python/issues/523
