### ISSUE TITLE
Allow setting SENTRY_RELEASE in Flask

### ISSUE THREAD

**Issue by joshma** [getsentry/raven-python#687]
Happy to send a PR, but this seems pretty simple to add / mostly wanted to check if I was doing this wrong. It seems like you can't set client.release right now if using the Flask integration, and there should be `SENTRY_RELEASE` configuration variable to do that.

I'm currently just doing `sentry.client.site = ...` instead.

**Comment by svenstaro** [comment]
@joshma I think you mean you are doing `sentry.client.release = ...` instead. Still, there should be an option to set this variable in flask and it should be documented.

**Comment by joshma** [comment]
:+1: thank you! (And oops, @svenstaro yeah I meant `sentry.client.release`, was doing it for site as well before I remembered the `SENTRY_SITE_NAME` config)
