### ISSUE TITLE
Django client assumes that users are always subclasses of AbstractBaseUser

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [getsentry/raven-python#695]
in a application i'm contributing to its not possible to use the base class,
since different field names are imposed due to a enterprise policy

**Comment by andialbrecht** [comment]
Starting with 5.10.1 the Django client doesn't require an instance of Django's BaseUser anymore. This was introduced in 475d379f09ab7981d892bd5ad0a0b45118d9e4f7.

This issue can be closed.

**Comment by untitaker** [comment]
@andialbrecht thanks for the update
