### ISSUE TITLE
failure to import the client class is hidden

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [getsentry/raven-python#696]
i made the mistake of using print statements on python3 with a extended django client class
django still started up however raven ceased to work silently

**Comment by RonnyPfannschmidt** [comment]
closing to get off my plate on github

**Comment by untitaker** [comment]
Just got a ping about this. The new sdk has a debug parameter which prints crashes to stderr.

We try very hard, both in the raven and the new sdk, to not take down the app even if the sdk crashes and becomes dysfunctional

**Comment by RonnyPfannschmidt** [comment]
I couldn't even produce context if I wanted to, shortly after I reported it I left the company to move across the country
