### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by qrilka** [getsentry/raven-python#704]
At https://docs.getsentry.com/hosted/clients/python/advanced/#client-arguments (from https://github.com/getsentry/raven-python/blob/master/docs/advanced.rst#client-arguments) I see
```
A Sentry compatible DSN as mentioned before
```
and yet there is no proper DSN description at that page.
This is at least confusing

**Comment by dcramer** [comment]
@qrilka you get this information via the Sentry server, which also guides you through this process. I dont think the documentation needs to spell it out more clearly, as a DSN (Data Source Name) is general terminology.

**Comment by qrilka** [comment]
then I guess you should replace "mentioned before" with "understood in general terminology"
of course it's your docs and if you prefer it to be confusing - ok
