### ISSUE TITLE
Error thrown when using django.contrib.sites, no settings.SITE_ID and manage.py

### ISSUE THREAD

**Issue by chriskief** [getsentry/raven-python#712]
An error is thrown when using django.contrib.sites (no settings.SITE_ID is defined) and an error is caught by Raven when executing a manage.py task:

```
$ python /www/360i/artifact/manage.py compress

DEBUG 2015-12-31 16:26:13,270 base 21307 140149553940288 Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x7f77149d2b10>
Error in sys.excepthook:
Traceback (most recent call last):
  File "/www/360i/local/lib/python2.7/site-packages/raven/base.py", line 215, in handle_exception
    self.captureException(exc_info=exc_info)
  File "/www/360i/local/lib/python2.7/site-packages/raven/base.py", line 698, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/www/360i/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 159, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/www/360i/local/lib/python2.7/site-packages/raven/base.py", line 529, in capture
    **kwargs)
  File "/www/360i/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 131, in build_msg
    data['tags'].setdefault('site', settings.SITE_ID)
  File "/www/360i/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'SITE_ID'
```

Looks like the code explicitly tries to grab the setting if no site can be found (which is always the case when running on the command line as there is no request).

```python
if not self.site and 'django.contrib.sites' in settings.INSTALLED_APPS:
    try:
        from django.contrib.sites.models import Site
        site = Site.objects.get_current()
        site_name = site.name or site.domain
        data['tags'].setdefault('site', site_name)
    except Exception:
        # Database error? Fallback to the id
        data['tags'].setdefault('site', settings.SITE_ID)
```

This setting may be omitted per the [Django docs] (https://docs.djangoproject.com/en/1.9/ref/contrib/sites/):

*The SITE_ID setting specifies the database ID of the Site object associated with that particular settings file. If the setting is omitted, the get_current_site() function will try to get the current site by comparing the domain with the host name from the request.get_host() method.*

**Comment by mattrobenolt** [comment]
I assume we can just do like, `if hasattr(settings, 'SITE_ID'): data['tags'].setdefault('site', settings.SITE_ID)`

Would be simpler, and I don't think it's a good idea that we introduce a query (from `Site.objects.get_current()`).

It's also not that big of a deal imo if `site` didn't get tagged because `SITE_ID` wasn't defined.

**Comment by chriskief** [comment]
To clarify, that query is already in the code...

https://github.com/getsentry/raven-python/blob/master/raven/contrib/django/client.py#L126

**Comment by mattrobenolt** [comment]
Oh, derp. I thought that was the proposal.

Then I'll fix this just to check for the attribute before assuming it exists.

**Comment by chriskief** [comment]
Awesome. Cheers!
