### ISSUE TITLE
Tornado logs any HTTPError even if not 5xx

### ISSUE THREAD

**Issue by ojii** [getsentry/raven-python#715]
In Tornado 3.2.2, raven 5.7.2 using ``raven.contrib.tornado.SentryMixin``, any ``tornado.web.HTTPError`` will be sent to sentry, even if their status code is not 5xx (for example a 403 will be reported).

**Comment by dcramer** [comment]
@ojii any thoughts on what a good solution to this would be? we're not tornado devs, so not overly familiar w/ the ecosystem

**Comment by ojii** [comment]
I've fixed this by changing ``SentryMixin. log_exception`` to check if ``value`` is an instance of ``tornado.web.HTTPError`` and ``500 <= value.status_code <= 599``.
