### ISSUE TITLE
[Support Request] How do I silence the extra copy of django 500 errors that Raven is producing?

### ISSUE THREAD

**Issue by coredumperror** [getsentry/raven-python#716]
My boss asked me to integrate Sentry logging into our django projects, and I was pleasantly surprised by the sheer ease of installation. However, I'm now frustrated because I'm getting 2 Sentry events for every 500 error, and I don't know how to silence the one I don't want.

What appears to be happening is that Sentry is logging every exception that my app throws, even when Sentry hasn't been configured in the `LOGGING` dictionary. So when I *do* configure it in `LOGGING` (I only want it to log errors from the `django.request` logger), I get two Sentry events: one for the raw exception, and one for the 500 error sent to `django.request`. Here's what that looks like in my Sentry logs: http://i.imgur.com/QuruFZZ.png

I want to remove the one that doesn't have a custom tag. How do I do that? I've tried setting every logger I could find in the Raven codebase to the 'null' logging handler, but that doesn't seem to help.

**Comment by dcramer** [comment]
To preface this, it's important to know Sentry is not logging. That also means we aim to integrate *outside* of logging. in Django's case, we hook a signal to do this. If you want to also capture events that happen in logs, you should configure LOGGING to bypass the Sentry handler in the cases that would also trigger the Django error handler (which is likely on in django.request)

If you want to add tags to request, you should approach it from a contextual perspective. That is, use ```client.tags_context(...)```, which should get picked up by the signal handler.

**Comment by coredumperror** [comment]
I want exactly the opposite of what you just said. I want Sentry to *only* activate in response to a `logging` event on the `django.request` logger. How do I disable the message that's sent to Sentry for exceptions? Something to do with signals?

**Comment by dcramer** [comment]
@coredumperror we don't support logging-only integrations in Django with the automated configuration. You can do it yourself by not using the Django integration, but fighting against these things will probably lead you to other limitations. As I mentioned, we're not log integration -- we aim to be crash reporting, which is why we hook into signals when possible.

**Comment by coredumperror** [comment]
So you're saying there's no way whatsoever to disable the crash report message being sent to Sentry?

**Comment by dcramer** [comment]
The Django integration is what includes the hooks. If you don't want those hooks you can simply choose not to use the Django integration and wire up your application however fits. The obvious caveats here being that you have to assume you're better at wiring things up than the collective we are:

https://docs.getsentry.com/hosted/clients/python/integrations/logging/

**Comment by coredumperror** [comment]
Ah, so all I had to do was *not* put `raven.contrib.django.raven_compat` into my `INSTALLED_APPS`. I learned how to hook sentry into logging here:
https://docs.getsentry.com/hosted/clients/python/integrations/django/#integration-with-logging
I hadn't realized that the `raven.contrib.django.raven_compat.handlers.SentryHandler` class was usable independently from `INSTALLED_APPS` entry.

**Comment by dcramer** [comment]
You *might* hit issues by using the Client and not having it in INSTALLED_APPS, but I'm definitely nota ware of any. It's primarily there to hook loading signals.
