### ISSUE TITLE
Connection refused from client when running under Cron

### ISSUE THREAD

**Issue by joedborg** [getsentry/raven-python#729]
If I run the following script locally (creds omitted), there is no problem:

```python
import raven
rc = raven.Client(dsn='http://sentry:9999/5')
rc.captureMessage('Hello')
```

But when I run this in a crontab (same user, same host), I get
```
Sentry responded with an error: <urlopen error [Errno 111] Connection refused> (url: http://sentry:9999/api/5/store/)
```

**Comment by dcramer** [comment]
A connection refused error is a networking error. It's not an HTTP error (which is the protocol Sentry utilizes). This means something is misconfigured with your network.

When you run "rc.captureMessage" it should be running in a thread, so its possible its not even reported (you could confirm on the server).

```
curl http://sentry:9999/api/5/store/
```

I'm closing this as im nearly positive there's nothing to do be done here in Raven/Sentry.
