### ISSUE TITLE
IOError: write error

### ISSUE THREAD

**Issue by Nihn** [getsentry/raven-python#732]
Hi,

After upgrading Raven from 5.3.1 to 5.10.2 we started getting these errors. It is only happening in Django projects (we have one Twisted and it works fine). No traceback available.

**Comment by eMerzh** [comment]
got the same error with a project that has raven 5.8.1
but not in another using 5.6... so the window of version is smaller :)

**Comment by mattrobenolt** [comment]
Do you also happen to be using uWSGI?

**Comment by eMerzh** [comment]
yes on both projects...
2.0.11.2 on the one that has errors and uWSGI==2.0.4 on the one that doesn't

**Comment by mattrobenolt** [comment]
Ah, so you'll want a few uwsgi options here. :) Likely, we weren't capturing the logging from uWSGI, and now we are.

But uWSGI logs these things for misbehaving clients. A write error would happen if the upstream got disconnected, but the backend process was still attempting to write to the closed socket.

You can add:

```ini
ignore-sigpipe = true
ignore-write-errors = true
disable-write-exceptions = true
```

This is what we run for Sentry to hush all of that noise.

**Comment by Nihn** [comment]
@mattrobenolt: thanks!

**Comment by Nihn** [comment]
@mattrobenolt Your solution silenced uwsgi errors but IOError still appears, is there anyway to ignore it on raven-python side?

**Comment by karloskar** [comment]
@Nihn: we hade the same problem as you but found out that there was a typo above.
```ini
disable-write-exceptions = true
```
should be
```ini
disable-write-exception = true
```
without the last s ([see uWSGI documentation](http://uwsgi-docs.readthedocs.org/en/latest/Options.html#disable-write-exception)).

**Comment by mattrobenolt** [comment]
Oh my. :( I've edited my comment to reflect the correct answer. Sorry about that!
