### ISSUE TITLE
captureException crashes when True is passed

### ISSUE THREAD

**Issue by alikefia** [getsentry/raven-python#735]
When passing True, the exec_info is not calculated (was the case before)
- This causes regressions in the client side
- May be also fix the code doc (https://github.com/getsentry/raven-python/blob/master/raven/base.py#L721)

**Comment by mattrobenolt** [comment]
Yeah, it seems like it'd definitely blow up here: https://github.com/getsentry/raven-python/blob/master/raven/base.py#L287

**Comment by mattrobenolt** [comment]
Looks like this behavior changed in 27cc40e6d5669e2275b89541711dea8bb6f6e309 which appears to have caused the regression.

/cc @mitsuhiko

**Comment by gmr** [comment]
Any ETA on when this will be released?

**Comment by mitsuhiko** [comment]
I thought this was released? Let me verify.

**Comment by mitsuhiko** [comment]
Oh I see. I will push out a release.

**Comment by gmr** [comment]
Thanks :)
