### ISSUE TITLE
AttributeError on MergeDict when trying to serialize deprecation warning for Django's req.REQUEST property

### ISSUE THREAD

**Issue by hheimbuerger** [getsentry/raven-python#739]
I'm using `request.REQUEST` in my Django 1.8 project, an attribute that is deprecated and will be removed in 1.9. This results in a deprecation warning (on `py.warnings`).

However, raven 5.8.1 doesn't seem to be able to serialize that, because I get a stacktrace on the `sentry.errors.serializer` logger.

    WARNING [Web/py.warnings] /app/myapp/views.py:286: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead. 
      if 'value' in request.REQUEST:
    WARNING [Web/py.warnings] /app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py:126: RemovedInDjango19Warning: `MergeDict` is deprecated, use `dict.update()` instead. 
      self._request = datastructures.MergeDict(self.POST, self.GET) 
    'MergeDict' object has no attribute 'dicts' 
    Traceback (most recent call last): 
      File "/app/.heroku/python/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform 
        return repr(value) 
      File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/datastructures.py", line 120, in __repr__ 
        dictreprs = ', '.join(repr(d) for d in self.dicts) 
    AttributeError: 'MergeDict' object has no attribute 'dicts' 
    ERROR [Web/sentry.errors.serializer] 'MergeDict' object has no attribute 'dicts' 
    Traceback (most recent call last): 
      File "/app/.heroku/python/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform 
        return repr(value) 
      File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/datastructures.py", line 120, in __repr__ 
        dictreprs = ', '.join(repr(d) for d in self.dicts) 
    AttributeError: 'MergeDict' object has no attribute 'dicts' 
    'MergeDict' object has no attribute 'dicts' 

I'll try upgrading raven next, but I couldn't find this being mentioned on the issue tracker or in the changelog.

**Comment by mitsuhiko** [comment]
I'm not sure this is related to raven. From what I can see this code that fails is in Django.
