### ISSUE TITLE
Regression in 5.11.0: AttributeError: 'NoneType' object has no attribute 'tb_frame'

### ISSUE THREAD

**Issue by nitr0man** [getsentry/raven-python#741]
When exception asserted with no stacktrace, raven also fails with exception in this place:
```
  File "..../raven/base.py", line 279, in _get_exception_key
    id(exc_info[2].tb_frame.f_code),
AttributeError: 'NoneType' object has no attribute 'tb_frame'
```

To reproduce - just call:
```
import sys
sys.excepthook(Exception, 'foo', None)
```
5.10.2 works OK.

**Comment by mitsuhiko** [comment]
Under what circumstances is the excepthook invoked without a stacktrace?

**Comment by nitr0man** [comment]
Unfortunatelly I don't know what really happened in this project. I just received stacktrace with this error (no other packages/project files were mentioned in it, just raven, trace starts in handle_exception).

**Comment by mitsuhiko** [comment]
Apparently celery's billiard module can cause this.

**Comment by nitr0man** [comment]
May be; celery is used here.
