### ISSUE TITLE
Bottle route is called two times when it fails

### ISSUE THREAD

**Issue by iurisilvio** [getsentry/raven-python#744]
I checked raven-bottle code, looks like you call the route two times.

https://github.com/getsentry/raven-python/blob/master/raven/contrib/bottle/__init__.py#L68

I'm not sure if this is intended. I think you can just re-raise the exception.

**Comment by dcramer** [comment]
Agreed -- this is absolutely not behavior that should be expected.

**Comment by dcramer** [comment]
I think the bottle middleware likely needs greatly cleaned up, and probably should just generally use the 'Sentry' wsgi middleware. That said, it should be resolved now, and I dont know bottle well enough to know what actually needs to exist vs doesn't.
