### ISSUE TITLE
Raven should not call functions on half-initialized objects.

### ISSUE THREAD

**Issue by Chronial** [getsentry/raven-python#747]
If an exception that was raised in a constructor is reported to sentry, raven will try to serialize all variables in the stacktrace, including the `self` in the constructor.

This results in raven calling `__repr__()` on uninitialized objects, which is definitely not safe. Raven should not try to serialize half-initialized objects (=object that are `self` in a function `__init__` somewhere in the stacktrace), but instead report something like `Unitialized[Classname]`.

The basic issue with this can be seen like this:
```
try:
    uuid.UUID('invalid')
except Exception:
    sentry_client.captureException()
```

**Comment by dcramer** [comment]
I'm not sure this is possible. How would we know if its initialized or not? We try/catch on serialization so this shouldn't be causing any issues. If it is, or you have further suggestions, please reopen.

**Comment by Chronial** [comment]
IMHO this might cause all kinds of issues, as it triggers undefined behavior. It shouldn't be too bad, as `repr` shouldn't have side-effects anyways, but it might. Maybe I have a class that caches something in a file and the not-yet-cached data is accessed in `repr`. Then the data is generated and written to a cache file, whose name is not properly initialized …

You can know that an object is not yet initialized by checking if the stack contains a function named `__init__`, where the object in question is referenced by a local variable named `self`.

**Comment by dcramer** [comment]
@mitsuhiko thoughts on ``__init__`` check?

**Comment by llchan** [comment]
I'd like to revisit this. If a ctor raises and repr fails, sentry/raven adds additional noise to the logs which has little to do with the actual exception.

I could silence the `sentry.errors.serializer` logger, but that may hide other more legitimate issues, so I think inspecting the stack before calling repr as proposed above is a better solution.

**Comment by Chronial** [comment]
@llchan In case you need a workaround, here's what I did for uuids:

```python
from raven.utils.serializer import register as register_serializer
from raven.utils.serializer import Serializer

class UUIDSerializer(Serializer):
    """Serializer for UUIDs that can handle half-initalized UUIDs"""
    types = (uuid.UUID,)

    def serialize(self, value, **kwargs):
        if hasattr(value, 'int'):
            # Fully initialized UUID
            return repr(value)
        else:
            # Not fully initalized UUID
            return "UUID(**unitialized**)"

register_serializer(UUIDSerializer)
```

**Comment by llchan** [comment]
Thanks @Chronial, appreciate the snippet.

I'm splicing raven into other people's scripts, so this approach of explicitly handling each type would grow cumbersome very quickly. When I get a chance I'll take a look at the serializer code and see if we can check if the exception was raised from an `__init__` func.
