### ISSUE TITLE
Do we have to reset the Context?

### ISSUE THREAD

**Issue by boussouira** [getsentry/raven-python#776]
Currently i do something like this in place 1:
```Python
except:
        raven_client.context.merge(raven_client.get_data_from_request(request))
        raven_client.captureException()
        raven_client.context.clear()
```
in place 2 a just capture the exception:
```Python
except:
        raven_client.captureException()
```

is the call to `raven_client.context.clear()` necessary in this scenario: 
User A raise an exception in place 1
User B raise an exception in place 2

will the exception in place 2 have the same request context as in place 1 if i didn't  call `clear()`?
What i want is that Raven automatically reset/clear the context after each request.

**Comment by dcramer** [comment]
You need to call ``context.clear()`` to flush out the context. Its often wise to have this done via a middleware or "start of request" hook. The builtin WSGI middleware does this, for example.

**Comment by boussouira** [comment]
Is it thread-safe or the context will be mixed up if we have more than one worker?

**Comment by dcramer** [comment]
We use thead locals so yes its threadsafe
