### ISSUE TITLE
What is the use of raven_compat?

### ISSUE THREAD

**Issue by Duologic** [getsentry/raven-python#784]
Hi

I see that `raven_compat` is used in the Sentry documentation: https://docs.getsentry.com/hosted/clients/python/integrations/django/

We've been running this without suffixing our imports with `.raven_compat`, but I was wondering what the past and current use is? And should we use it?

If it is not the case, why is it still documented that way?

Thanks!

**Comment by mitsuhiko** [comment]
It's a workaround for older Django versions. It can still be used this way. We will probably keep it in the docs for now.

**Comment by Duologic** [comment]
Thanks.
