### ISSUE TITLE
How to configure Python Middleware without settings.py

### ISSUE THREAD

**Issue by alculquicondor** [getsentry/raven-python#785]
I'm migrating settings to Django Constance, which allows to set settings from admin page. How could I tell raven to take the DSN from there? Is there a way to override the client?

https://cdnamigocloud.global.ssl.fastly.net/dashboard/img/amigocloud_logo_forwhitebackground.png

**Comment by dcramer** [comment]
All I can say is "I dont know". You should take this up with the Django Constance project as its unrelated to our SDK.
