### ISSUE TITLE
release feature with myapp.__version__

### ISSUE THREAD

**Issue by aleprovencio** [getsentry/raven-python#797]
Hello, any reason why Sentry does not seem to detect my RELEASE setting put this way:

    import myapp
    RAVEN_CONFIG = {
        'CELERY_LOGLEVEL': env.int('DJANGO_SENTRY_LOG_LEVEL', logging.INFO),
        'DSN': SENTRY_DSN,
        'RELEASE': myapp.__version__,
    }

**Comment by dcramer** [comment]
You need to use lowercase attributes names IIRC. If that doesn't work let us know and we'll re-open this ticket.

**Comment by aleprovencio** [comment]
Thanks for the quick answer @dcramer. Unfortunately using lowercase yields the same message from the "Releases" tab: "There don't seem to be any releases yet."

**Comment by dcramer** [comment]
@aleprovencio what version of the SDK?

**Comment by aleprovencio** [comment]
This is raven-python 5.21.0

**Comment by dcramer** [comment]
I can't explain how it'd happen at this point. You should be able to import the client and do $client.release to confirm it's actually set, but our Django integration is definitely reading that config value.

**Comment by dcramer** [comment]
Is it possible you're configuring RAVEN_CONFIG after settings have already been loading? Sentry won't re-evaluate the client when settings change, and I cannot reproduce this issue (we use this exact same kind of configuration ourselves).

**Comment by aleprovencio** [comment]
Please have look at [cookiecutter-django](https://github.com/pydanny/cookiecutter-django) which is what I'm using. They still don't have a "release" setting on their implementation, so I was thinking of making a PR there as soon as I get this to work.

**Comment by pydanny** [comment]
@aleprovencio did you ever get this functioning with Cookiecutter Django? If so, please send a pull request to the project. The more we can provide support for Sentry and Raven usage the better.

**Comment by aleprovencio** [comment]
I wish I had @pydanny :(
Will try to make more tests in a few days and promise to post relevant info if any OK?

**Comment by webyneter** [comment]
@aleprovencio any news on that with regards to Cookiecutter Django?

**Comment by aleprovencio** [comment]
I'm so sorry I've completely forgotten about this issue. Unfortunately I don't have nowadays a single cookiecutter project on production which I have access to test this. If no one can test this now, I might start a new project in three months.
