### ISSUE TITLE
Raven sending a lot of data to Django log on timeout

### ISSUE THREAD

**Issue by boussouira** [getsentry/raven-python#799]
In this line:
https://github.com/getsentry/raven-python/blob/105fdf3fa5091ab1eccb894cfad34560e097622d/raven/base.py#L630

Raven will send `data` to the log file, which print a lot of lines, we are using PaperTrail ad this make our daily usage very high.

is there a way to stop raven from printing `data` content to the log?

**Comment by dcramer** [comment]
I'm totally ok with removing data from the actual message itself. We can still provide data in 'extra' in case people want access to it. Would you be interested in submitting a PR to do so?

**Comment by boussouira** [comment]
I'll submit a PR, just not sure what you mean by `extra`?  you mean the context extra data?

**Comment by dcramer** [comment]
@boussouira i simply meant the 'extra' argument of the logging function

```
logging.info('test', extra={'data': data})
```

Then log handlers can access data if they want.

**Comment by boussouira** [comment]
Fixed in 3c6496a0
