### ISSUE TITLE
raven causing odd return value for traceback.format_exc()?

### ISSUE THREAD

**Issue by cjerdonek** [getsentry/raven-python#804]
While using `raven-python`, we got a few errors recently suggesting that Python's `traceback.format_exc()` returned a strange value when the error was reported to Sentry. The value looked like the following in the Sentry UI (with the single quote on the second line):

    'NoneType
    '

I see lots of issues in this repo mentioning `NoneType`, so I thought I'd ask if you think raven is the culprit here.

Below are more details.

We're using raven 5.23.0, Django 1.9.7, and Python 3.5.2.

Because of issue #550 (exception chaining), we added a custom `SENTRY_CLIENT` that simply adds the value of `traceback.format_exc()` to the `extra` dict inside `captureException()`. We are doing this to get the full exception chain.

This has always worked fine, except in the case I'm reporting here.  A few times when running a custom management command, the Sentry UI shows the above `NoneType` value under "Additional Data" (where the extra dict is displayed), instead of the text of an exception chain.

Since the exception chain didn't display, I don't know what caused the issue, and I'm not sure if it's reproducible yet.

Does `raven-python` do anything that might interfere with the return value of `traceback.format_exc()`? Thanks.

**Comment by dcramer** [comment]
The exception stacktrace follows the same rule of garbage collection as the rest.

For example:

```
def main():
    try:
        1 / 0
    except:
        pass

main()

import sys
sys.exc_info()

import traceback
traceback.print_exc()
```

The exception gets garbage collected, and to avoid being wrong as I dont know the entirety of the internals, this likely happens when it is no longer referenced. Our Python SDK does a bunch to clean up its own references of the exception, but effectively the third item in ``exc_info`` is the traceback, and once its gone you can't recover it.

**Comment by cjerdonek** [comment]
Okay, thanks for your response, @dcramer. I believe I know the cause now, which is supported by your reply.

Basically, raven is "double logging" when a management command is being run (see issue #802). And since the first logging event does "garbage collection" as you describe, the chained exception is missing from the second logging event (which is the record I was looking at and reporting on for this issue).

[My comment](https://github.com/getsentry/raven-python/issues/802#issuecomment-233550518) on issue #802 has more information, including a pointer to where raven is double logging when a management command is being run.
