### ISSUE TITLE
Logging exceptions prevent responses on App Engine with Flask

### ISSUE THREAD

**Issue by brianmhunt** [getsentry/raven-python#816]
I have what I expect is the quintessential setup with Google App Engine + Flask + Raven, so I would expect this to be a common problem.

The issue is that when one calls e.g. `logging.error` with Raven capturing logging the Flask endpoint never completes.  It just hangs.  Example for reproduction is below.

I did a little debugging and Flask, for its part, seems to finish its `wsgi_app` requests as expected, so the problem seems to be with Google App Engine.

I am running OS X 10.11.6, App Engine 1.9.38 development app server via homebrew.

## Steps to reproduce (minimum working example)

1. `mkdir ae-sentry`
2. `cd ae-sentry`
3. `virtualenv pyve`
3. `./pyve/bin/pip install raven[flask]`

Then create:

### `appengine_config.py`

```python
from os import path
from google.appengine.ext import vendor
vendor.add(path.abspath(path.join(path.dirname(__file__), 'pyve')))
```

### `app.yaml`

```yaml
application: dummy
version: test
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: ssl
  version: latest
```

### `app.py`

```python
import sys
import logging

sys.path.insert(0, 'pyve')

from flask import Flask, make_response
from raven.contrib.flask import Sentry

app = Flask('test')

sentry = Sentry(app, logging=True, level=logging.ERROR)
# Note, we get SENTRY_DSN from environment

@app.route('/')
def test():
    # Comment the following logging.exception and the endpoint works.
    # Uncomment it, and it never completes.
    #  logging.exception("Boo!")
    return make_response("ok")
```

Finally, reproduce at will with  `dev_appserver.py .` and opening `localhost:8080` in a browser.

**Comment by brianmhunt** [comment]
Incidentally, the workarounds in #514, being https://github.com/getsentry/raven-python/issues/514#issuecomment-122237133:

> init sentry with Sentry(app, wrap_wsgi=False) or sentry.init_app(app, wrap_wsgi=False) or re-override the wsgi_app using ... 

```python
if isinstance(app.wsgi_app, Sentry):
    app.wsgi_app = app.wsgi_app.application
```

do not resolve this problem.

**Comment by brianmhunt** [comment]
It looks like the problem was the [asynchronous transport](https://docs.getsentry.com/hosted/clients/python/transports/), and there are two solutions:

### 1. Use a synchronous transport e.g.

```python
from raven.transport.http import HTTPTransport
app.config['SENTRY_TRANSPORT'] = HTTPTransport
```

### 2. Employ a deferred send in an AppEngin'y way

For example, the  [raven-appengine](https://github.com/danielchatfield/raven-appengine) package.

##  Fix?
Obviously it would be worthwhile for this to appear in the docs for Raven[Flask], or for it to complain about it's running on AppEngine and the transport is asynchronous.

While I have resolved the issue for myself, I will leave this open for visibility about the documentation issue

**Comment by dcramer** [comment]
I think what we should do here is one of two things:


1. sentry-python-appengine which contains the transport/etc and configures defaults differently
2. ensure we have a fully compatible appengine transport in core, and feature detect to use it as a default in these situations.

**Comment by brianmhunt** [comment]
Those are both better than my suggestion. 😀

To detect AppEngine, look to the environment variables, here: 

https://cloud.google.com/appengine/docs/python/how-requests-are-handled#Python_The_environment

**Comment by jmgirven** [comment]
I am still having problem with this. I have:

raven[flask]==5.32.0

    from raven.contrib.flask import Sentry
    sentry = Sentry(app, dsn="...")
    sentry.captureException(data={...})

I am receiving the report in sentry, but my end point is hanging when the exception is sent. The endpoint is fine if captureException isn't called. Is there something I am missing?

**Comment by eyalev** [comment]
It didn't work for me as well.

It worked only when I explicitly set HTTPTransport:

```
from raven import Client
from raven.transport.threaded import HTTPTransport

client = Client(
    'https://public_key:secret_key@sentry.io/project_id',
    transport=HTTPTransport
)

try:
    1 / 0
except ZeroDivisionError:
    client.captureException()
```

**Comment by brianmhunt** [comment]
@eyalev  You might want to open a new issue, referencing this one, and give details of your setup.
