### ISSUE TITLE
TypeError: unhashable type: 'set' due to commit 93dd4ab82fd611812392d760f577b2fe71f80f19

### ISSUE THREAD

**Issue by benjolitz** [getsentry/raven-python#822]
I've commented here:
https://github.com/getsentry/raven-python/commit/93dd4ab82fd611812392d760f577b2fe71f80f19#commitcomment-18527777

Effectively, a stray comma has created a tuple out of what should've been just a set.

A set consuming a tuple of a set is unhashable, whereas the previous code had lacked a comma that lead to a set consuming a set (a safe operation).

Deleting that comma will fix the issue.

Raven-python 5.24.0 break for Flask applications, which is rather unfortunate as I now have to force the 5.23.X series for my deployments.

**Comment by adepue** [comment]
👍  this is hitting us as well

**Comment by jtillman** [comment]
👍

**Comment by adepue** [comment]
@dcramer FYI this has broken a fair number of things for us today where we have auto upgrades of raven set up.  We are in the process of pinning backwards, but would love to have a fix soon.

**Comment by RVoigtHearsay** [comment]
👍

**Comment by olakd** [comment]
👍

**Comment by droanr** [comment]
👍

**Comment by dcramer** [comment]
Sorry all! Clearly our test coverage for Flask isn't great. This is fixed in 5.24.1

**Comment by adepue** [comment]
Thanks @dcramer!
