### ISSUE TITLE
raven-flask ONLY working if SENTRY_DSN env variable is set

### ISSUE THREAD

**Issue by cjmielke** [getsentry/raven-python#823]
Using Sentry with Flask, either standalone or with uWSGI, works if I have the SENTRY_DSN environmental variable set (either on command line or defined in the uwsgi configuration file)

However, setting the dsn with the kwarg in the python source does not work. Ever. Ive been digging through the source trying to figure out why. I am formatting the string exactly.

I have reproduced this finding on two different flask installations and two web servers.

**Comment by ehfeng** [comment]
This should be fixed in https://github.com/getsentry/raven-python/commit/e03c642d689ff9d69ba1e2f3cb08c52ea89c2db0

Please update your Sentry SDK (`pip install -U raven[flask]`) and try again. Please re-open another ticket if you're still seeing problems.
