### ISSUE TITLE
TypeError: unhashable type: 'set' | Regression/semver break with raven[flask] 5.24.0

### ISSUE THREAD

**Issue by Daenyth** [getsentry/raven-python#834]
In 5.23.0 this code works in my app:

```python
from raven.contrib.flask import Sentry
sentry = Sentry(dsn=sentry_dsn)
sentry.init_app(my_flask_app, logging=True, level=logging.ERROR)
```

In 5.24.0 this throws `TypeError: unhashable type: 'set'`

```
  File "/home/user/foo/application.py", line 63, in prepare_app
    sentry.init_app(my_flask_app, logging=True, level=logging.ERROR)
  File "raven/contrib/flask.py", line 258, in init_app
    self.client = make_client(self.client_cls, app, self.dsn)
  File "raven/contrib/flask.py", line 49, in make_client
    'app': app,
  File "raven/base.py", line 165, in __init__
    self.include_paths = set(o.get('include_paths') or [])
```

**Comment by dcramer** [comment]
What version of Python are you using?

```
>>> set(set())
set([])
```

(this has nothing to do with semver, its not an intentional backwards incompat)

**Comment by dcramer** [comment]
Actually realizing that 'o' could somehow be a set. Are you defining RAVEN_CONFIG or SENTRY_CONFIG in app.config?

**Comment by mitsuhiko** [comment]
sounds like the return value of `o.get('include_paths')` includes a set. eg:

```
>>> set([set([1, 2, 3])])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'set'
```

**Comment by dcramer** [comment]
I'm unclear as to what the behavior is here, but it sounds like you have some bad value which may have accidentally worked on a previous version. If you can confirm the value of ``o['include_paths']`` it will likely tell the full story.

Closing this until there's something more we need to do.
