### ISSUE TITLE
CaptureMessage spawns zombie threads

### ISSUE THREAD

**Issue by WhackoJacko** [getsentry/raven-python#837]
> Operating System: Debian GNU/Linux 8 (jessie)
> Kernel: Linux 3.16.0-4-amd64
> Architecture: x86-64

How to reproduce:

```
from raven import Client
Client(dsn='some-sentry-dsn').captureMessage(u'Test')
```

Every call of captureMessage spawns thread, which further does not get killed.

**Comment by mattrobenolt** [comment]
It's not every call to captureMessage, it's every instance of Client. You should only need to create one client. Don't create a new client every time you want to send a message.

**Comment by WhackoJacko** [comment]
thanks for clarification!
