### ISSUE TITLE
Cannot identify HEAD for git repository.

### ISSUE THREAD

**Issue by Fajkowsky** [getsentry/raven-python#855]
I have 
django 1.8
python 3.5
raven 5.26.0
 And I have followed django integration after executing:

`python3 projectname/manage.py raven test`

I have got
`
raven.exceptions.InvalidGitRepository: Cannot identify HEAD for git repository at /home/faja/Pulpit/Projekty/mainProjectFolder/djangoFolder/mainAppWithSettings`

My project structure

```

zdobadzszczyt/
└── zdobadzszczyt
    ├── config
    ├── landingpage
    │   └── migrations
    ├── socialauth
    │   └── migrations
    ├── static
    ├── staticfiles
    │   └── admin
    │       ├── css
    │       ├── img
    │       │   └── gis
    │       └── js
    │           └── admin
    ├── templates
    └── workout
        ├── management
        │   ├── commands
        └── migrations

```

**Comment by hmilkovi** [comment]
+1

**Comment by laurentS** [comment]
I think it's a documentation issue. I followed the quick installation instructions on my sentry instance, which suggests this line

    'release': raven.fetch_git_sha(os.path.dirname(__file__)),

in your `settings.py`. But if your `settings.py` is like mine one folder down from your git root folder, then you get the error you describe (because of this: https://github.com/getsentry/raven-python/blob/master/raven/versioning.py#L22). Instead follow https://docs.sentry.io/clients/python/integrations/django/ and replace the line with:

    'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),

and you're in business!

**Comment by hmilkovi** [comment]
I was stupid, I had bad path set to git repo root, now all works well, thx :)

**Comment by megha-n-bodke** [comment]
git repo root should be specified in raven.fetch_git_sha().
Below line can be used to test the path value. For incorrect path, it will return above reported error.
`python -c 'import raven; raven.fetch_git_sha("../../")`

I think, we can close this issue :)

**Comment by ACPK** [comment]
@Fajkowsky @megha-n-bodke - Having this issue on Heroku despite the updated release path.

**Comment by tony** [comment]
That won't work on heroku.

As of July 18th, 2017:

- The git information isn't there
- You have to grab the ``SOURCE_VERSION`` environmental variable during *builds* (https://devcenter.heroku.com/changelog-items/630)
- But heroku disregards that during actual running service

So: 

1. Use this buildpack to keep the ``SOURCE_VERSION`` in your deployments

   ``$ heroku buildpacks:add https://github.com/ianpurvis/heroku-buildpack-version`` (https://elements.heroku.com/buildpacks/ianpurvis/heroku-buildpack-version)

2. Then do this in your settings:

```python
RAVEN_CONFIG = {
    # 'dsn': 'https://....',
    'release': os.environ['SOURCE_VERSION']
}
```

**Comment by dcramer** [comment]
There is also this feature which should be helpful:

https://devcenter.heroku.com/articles/dyno-metadata

**Comment by rizwanoffice** [comment]
make sure path is correct. try to use os.path.dirname to go one level up the directory.

**Comment by Designer023** [comment]
I have tried all of the above and it didn't work for a Django Project I have been working on. We're using Heroku also if that is relavant. What eventually worked for me is:

```
'release': raven.fetch_git_sha(os.path.abspath(BASE_DIR)),
```

Where BASE_DIR is set in the settings file which resides in the project folder one level up from the root of the project. The project settings file is specified using an environmental variable:
```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
````

**Comment by elcolie** [comment]
```bash
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/source/poinkbackend/config/settings/local.py", line 76, in <module>
    'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),
  File "/usr/local/lib/python3.6/site-packages/raven/versioning.py", line 25, in fetch_git_sha
    'Cannot identify HEAD for git repository at %s' % (path,))
raven.exceptions.InvalidGitRepository: Cannot identify HEAD for git repository at 
Service 'backend' failed to build: The command '/bin/sh -c python manage.py compilemessages' returned a non-zero code: 1
ERROR: Job failed: exit status 1
```

`'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),` works fine on my local
But when I deploy my Django app to AWS EC2. I use docker container and I copy only source code.
How can I use it without `.git`?

**Comment by elcolie** [comment]
Oh. Just comment of make it works!

**Comment by oldcai** [comment]
```
import raven
RAVEN_CONFIG = {
    'dsn': '***',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    'release': raven.fetch_git_sha(os.path.abspath(os.getcwd())),
}
```

`os.getcwd()` works for me.
