### ISSUE TITLE
New Warning on Django 1.10 after commit c3e504a0bf77deb9a79bd841e9cacc62c8127901

### ISSUE THREAD

**Issue by rubendura** [getsentry/raven-python#870]
On commit c3e504a0bf77deb9a79bd841e9cacc62c8127901 a new function install_middleware() is added to raven/contrib/django/models.py .

This function seems to be trying to install the Sentry middleware if they are not manually added to settings, but seems to be ignore the new middleware style introduced in Django 1.10.
As this function only checks settings.MIDDLEWARE_CLASSES the middleware is always added to that setting when using the new MIDDLEWARE setting, which causes a warning when running the check management command from Django.

**Comment by AlJohri** [comment]
Bumping this issue. Getting the same warning:

```
?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.
```

For reference, please check out `django-debug-toolbar` perspective on automatic setup.

They removed automatic setup in their latest version (1.6).
http://django-debug-toolbar.readthedocs.io/en/1.6/changes.html#removed-features
> Support for automatic setup has been removed as it was frequently problematic. Installation now requires explicit setup.

Previous version (1.5) of their documentation elaborated on this.
http://django-debug-toolbar.readthedocs.io/en/1.5/installation.html#automatic-setup
>The automatic setup is known to interfere with the start-up sequence of some projects and to prevent them from loading or functioning properly.
>The explicit setup described below is recommended for all but the most trivial projects. The automatic setup is kept for backwards-compatibility.

**Comment by fengsi** [comment]
https://github.com/getsentry/raven-python/pull/883

**Comment by mitsuhiko** [comment]
This will be fixed in next release.
