### ISSUE TITLE
Django Templatetag for getting release identifier

### ISSUE THREAD

**Issue by nuschk** [getsentry/raven-python#875]
We already use the sentry_public_dsn template tag to keep server and client configuration in sync. It would be cool to have the same for the release identifier. 

Could be as simple as this:

```
@register.simple_tag
def sentry_release(scheme=None):
    from raven.contrib.django.models import client
    return client.release
```

**Comment by dcramer** [comment]
Generally -1 on this approach as it opens a can of worms. e.g. what about environment? does it also get its own template tag? where do we stop?

I think we could provide a context processor which exposes the Sentry config, but it's pretty easy to also provide your own (which is what we do).

More importantly, I think it's rare that you would want JS and Python errors in the same project (we focus on a project being a service these days), so I think the applicability of this is fairly low.

**Comment by nuschk** [comment]
Yeah, but then why have the template tag for the DSN in the first place, if it's considered such an anti-pattern? That code is implying to a) use the same project for client and server and b) use template tags instead of template preprocessors.

We are actually doing what you describe in production now (we use a single project though, your use-case may not be for everybody) and found out about the template tag only yesterday upon re-reading the documentation. So I thought that would be the preferred way of configuring the client (the documentation isn't implying otherwise).

**Comment by dcramer** [comment]
@nuschk our use case is what we are building :)

It's very complex, and noisy to mix in all events into a singular service. It might be ok for a very small scale project, but everything we're building in Sentry is about splitting projects by services.

I agree that the DSN helper may not make sense these days, but we're also likely not going to remove it, especially now that the public DSN is also used for the feedback module.

**Comment by nuschk** [comment]
I'm not actually arguing with you, I agree with everything you said. 

It's just that a 'service' for us is deployable unit, which *might* combine some client and server code. You'll want to roll back the deployment regardless of whether the increase in error rate is coming from front- or backend. In this case the shared project is kinda the obvious choice (I'm not saying it's the best, I just haven't put much thought in it). 

But, I'm here to learn, and since you seem to operate at larger scale, might I ask how you do that?

**Comment by dcramer** [comment]
@nuschk there's no concern on Sentry's side whether things are duplicated (like the version of the app), and in most situations you will be deploying the app in stages. e.g. you can't serially deploy both the frontend and backend components. Because of this there are still multiple services, even if they share the same code.
