### ISSUE TITLE
Missing raven.contrib.tornado.SentryMixin sphinx reference

### ISSUE THREAD

**Issue by kvdb** [getsentry/raven-python#878]
I added the following entry to my project `intersphinx_mapping`:

`https://raven.readthedocs.io/en/latest`

It seems that not all documentation is exported there, given the following error:

`py:class reference target not found: raven.contrib.tornado.SentryMixin
`

**Comment by mitsuhiko** [comment]
We no longer support `raven.readthedocs.io`. Unfortunately intersphinx is not supported by our current doc setup.
