### ISSUE TITLE
[Feature request] More breadcrumbs configuration options

### ISSUE THREAD

**Issue by bluefish6** [getsentry/raven-python#880]
Hi,

We just updated raven and sentry and we were very happy with the "new" breadcrumbs feature.
However, our excitation faded away, when we found out that each new event on sentry intead of taking ~0,5kb, now takes ~70kb. This means that our HDD usage would rise 100x from what we have now.
When dealing with Really Big Crashes (resulting in hundreds of events per second), 100-fold rise in HTTP transfer is 100 times more likely to hang both the application and sentry. That's the price we cannot afford to pay for some extra information provided by breadrumbs.

In fact, we would love to use Breadcrumbs, but on a much smaller scale, say 10 breadrumbs.

For this we need the option to set the size of breadcrumbs buffer lower than the default limit 100. However, currently there is no way of providing this via any setting, argument or keyword argument - see https://github.com/getsentry/raven-python/blob/master/raven/breadcrumbs.py#L76

On the other hand, raven-js supports this out of the box via maxBreadrumbs setting ( https://docs.sentry.io/clients/javascript/config/ ). It would be very nice to introduce this to raven-python as well :)

**Comment by dcramer** [comment]
I'm fine with making this configurable but it's not a real problem in my eyes. Its 70k raw which is far less gzipped. 

To be clear, python events are already often 30-40k so if you were managing to fit into .5k before you have abnormally lightweight data.

**Comment by bluefish6** [comment]
To shed more light on the issue:

We actually have the following sizes (as indicated by Sentry next to JSON download link):
- <1 kilobyte for simple `logging.warning` events with very little (or none) `extra` data (*example at the end)
- ~1.5-3 kilobytes for complicated `logging.warning` events with a lot (or big, like requests or responses body) of extra data
- 15-30 kilobytes for `logging.exception` events with full tracebacks
- 70+ kilobytes for `logging.warning` events without tracebacks or any `extra` data, but with breadcrumbs

We haven't tested yet `logging.exception` events with breadcrumbs, rich `extra` data and tracebacks.

@dcramer I'm not sure what happens next. On one hand, you mentioned that you're "fine with making this configurable", but on the other hand you closed this issue. Is that a **WONT_FIX**, **FUTURE_MILESTONE** (any hint on ETA?) or **PULL_REQUEST_WELCOME**?

Thanks!

*example <1kb event:
`{"id":"19ace543aa674a839cb6e29d28ec5840", "project":7, "release":"1.0", "platform":"python", "culprit":"root in _log_error", "message":"foobar: could not convert string to float: foobar", "datetime":"2016-09-29T18:51:51.000000Z", "time_spent":null, "tags":[["level","error"],["logger","root"],["server_name","app-01"],["sentry:release","1.0"]], "extra":{"threadName":"'uWSGIWorker15Core0'", "thread":140323366643520, "process":19554, "sys.argv":["'uwsgi'"], "hostname":"'app-01'", "filename":"'foobar.py'", "processName":"'MainProcess'", "pathname":"'/home/user/foo/bar.py'", "lineno":147, "asctime":"'2016-09-29 19:00:04,031'"}, "fingerprint":["{{ default }}"], "modules":{"python":"2.7.6"}, "received":1475175111.0, "sentry.interfaces.Message": {"message":"foobar: could not convert string to float: foobar"}, "version":"6"}
`

**Comment by dcramer** [comment]
I closed it as we don't use issue trackers for future requests and at this time won't be implementing the feature ourselves.
