### ISSUE TITLE
middleware ClosingIterator() does not always call iterable.close()

### ISSUE THREAD

**Issue by toffer** [getsentry/raven-python#885]
I work at New Relic, and we have several customers who have reported the issue described in this post on the Sentry forum:

* https://forum.sentry.io/t/sentry-wsgi-wrapper-and-new-relic-apm/291

The issue is that customers who use both the Sentry WSGI middleware and the New Relic Python agent were seeing transaction times that were dramatically wrong. Durations were too long by orders of magnitude. When digging in to see why this happens, we narrowed the cause down to a recent change to how the Sentry WSGI middleware was calling `close()` on the iterable returned by the WSGI application. (See commit 10d0774a8c7d2e04e92dd97af1de7079a6441bb1 from Aug 19 as part of PR #836.)

And, it turns out that this impacts not just applications that use New Relic, but also any Django application.

## The problem

In `ClosingIterator.__init__()`, `self.iterable` is assigned the value of `iter(iterable)`:

```python
class ClosingIterator(Iterator):
    ...
    def __init__(self, sentry, iterable, environ):
        ...
        self.iterable = iter(iterable)
```

Later, in `ClosingIterator.close()`, there's a check to see if `self.iterable` has a `close()` method, and if it does, it calls it:

```python
class ClosingIterator(Iterator):
    ...
    def close(self):
        ...
        try:
            if hasattr(self.iterable, 'close'):
                with common_exception_handling(self.environ, self.sentry):
                    self.iterable.close()
```

The problem is that the original `iterable` and `self.iterable` are not necessarily the same object, which means that calling `self.iterable.close()` does not necessarily call `iterable.close()`. That's because calling `iter(iterable)` does not always return the original iterable, but instead it can return an entirely different iterator.

It all depends on how the original `iterable` is defined. If it is defined with an `__iter__` method that returns `self`, then everything is good. That means that `assert iterable is iter(iterable)` is `True`.

That's how the iterable from a Flask/Werkzeug application is defined. It's a `werkzeug.wsgi:ClosingIterator` object, where `__iter__` is defined like this:

```python
class ClosingIterator(object):
    ...
    def __iter__(self):
        return self
```

Example:

    In [61]: werk_resp = werkzeug.Response()

    In [62]: app_iter = werk_resp.get_app_iter({'REQUEST_METHOD': 'GET'})

    In [63]: app_iter
    Out[63]: <werkzeug.wsgi.ClosingIterator at 0x1039f9d10>

    In [64]: iter(app_iter)
    Out[64]: <werkzeug.wsgi.ClosingIterator at 0x1039f9d10>

However, there are other cases where `assert iterable is iter(iterable)` is `False` because what is returned from `iter(iterable)` is different from the original iterable. In Django, for example, `django.http.response:HttpResponse` defines `__iter__` like this:

```python
class HttpResponse(HttpResponseBase):
    ...
    def __iter__(self):
        return iter(self._container)
```

Example:

    In [52]: dj_resp = django.http.HttpResponse()

    In [53]: dj_resp
    Out[53]: <django.http.response.HttpResponse at 0x1039f9b90>

    In [54]: iter(dj_resp)
    Out[54]: <listiterator at 0x1039f9750>

When that's the case, calling `close()` on the result of `iter(iterable)` does not call the `close()` method on the original `iterable`.

## Possible solution

I think the answer is to save away the close method of the original `iterable`:

```python
class ClosingIterator(Iterator):
    ...
    def __init__(self, sentry, iterable, environ):
        ...
        self.iterable = iter(iterable)
        self.iterable_close = getattr(iterable, 'close', None)
```

so that it's possible to call it in `close()`:

```python
    def close(self):
        ...
        try:
            if self.iterable_close:
                with common_exception_handling(self.environ, self.sentry):
                    self.iterable_close()
```

I would be happy to submit a pull request with this fix (and tests), but I thought I would run this by you first before I did.

cc: @tkrajcar

**Comment by mitsuhiko** [comment]
Thanks for the report. I will take a look at that.

**Comment by toffer** [comment]
Thanks! Appreciate the speedy resolution!
