### ISSUE TITLE
Django integration changes the type of MIDDLEWARE_CLASSES

### ISSUE THREAD

**Issue by GaretJax** [getsentry/raven-python#890]
Would it make sense for https://github.com/getsentry/raven-python/blob/master/raven/contrib/django/models.py#L240-L243 to check for the type of `MIDDLEWARE_CLASSES` (either `list` or `tuple`) and patch the settings accordingly?

We currently rely on `MIDDLEWARE_CLASSES` being a `list` further down in the codebase and different packages we pull in, and when raven is installed, this assumption is broken. It could be fixed in those places as well, but I think that not altering the type when patching settings in a non-transparent way would be the correct behavior. It is also very hard to find the place where this conversion occurs if the only error we get is a stacktrace in a completely different part of the codebase.

If this is accepted, I volunteer to work on a PR to propose a fix.

**Comment by fengsi** [comment]
@GaretJax agree on the not altering the original type behavior 👍

**Comment by dcramer** [comment]
@GaretJax I think thats totally fine. We should impact the application as little as possible, and changing types doesn't align with that goal.

**Comment by mitsuhiko** [comment]
Going to change that.

**Comment by GaretJax** [comment]
That was fast, thanks a lot!
