### ISSUE TITLE
Fix installation docs

### ISSUE THREAD

**Issue by lorddaedra** [getsentry/raven-python#891]
Docs should mention MIDDLEWARE(_CLASSES). Currently by default Sentry try to monkey patch my settings.py and it's ugly way. It's not PHP, do not try to do something, which user can do during installation, *at least by default*.

( My opinion about it all here https://github.com/getsentry/raven-python/pull/860#issuecomment-255297333 )

You should at least tell user to set it (edit here https://docs.sentry.io/clients/python/integrations/django/ ). (Also correct order for MIDDLEWARE(_CLASSES) is matter)

**Comment by dcramer** [comment]
We're happy to accept PRs to docs, but its not our intention to document every API we hook into "just because".
