### ISSUE TITLE
Raven logs executable path instead of module function 

### ISSUE THREAD

**Issue by gsakkis** [getsentry/raven-python#895]
I upgraded raven from 5.19.0 to 5.31.0 and noticed that exceptions on Sentry are logged at the top level as `{{exception class}} {{executable absolute path}}` in place of `{{exception class}} {{package}}.{{module} in {{callable}}`. Hopefully this is a bug instead of a feature because all exceptions now show the same executable and I have to drill down to the traceback to figure out where the exception is raised.

**Comment by dcramer** [comment]
@gsakkis this is the transaction name -- its possible using the executable by default isn't a good idea due to lack of instrumentation.

What framework/toolkit are you using? It may be as easy as instrumenting yourself, or us adding some basics to the default WSGI middleware.

**Comment by mitsuhiko** [comment]
Some examples of before and after would be great. If you want you can mail me that personally if you don't want it in the tracker.

**Comment by gsakkis** [comment]
I am using [RQ](http://python-rq.org/). The relevant raven configuration is:

    import raven
    import rq
    import rq.contrib.sentry

    worker = rq.Worker(...)
    client = raven.Client(sentry_dsn, transport=RequestsHTTPTransport)
    rq.contrib.sentry.register_sentry(client, worker)

**Comment by dcramer** [comment]
@gsakkis not being an expert in RQ here, do you happen to know if theres any kind of signals we could hook for "before a task is executed" and after. Basically we'd want to call raven.transactions.push('task name'), and then pop() it on the end of execution.

**Comment by dcramer** [comment]
fyi this is the culprit of the behavior we may want to remove as a default:

https://github.com/getsentry/raven-python/blob/f9e9bcd28051e7193969e0c495a1cd413df3e29f/raven/base.py#L193

**Comment by gsakkis** [comment]
RQ allows for custom exceptions handlers, in fact that's how `register_sentry` is defined:
```
def register_sentry(client, worker):
    """Given a Raven client and an RQ worker, registers exception handlers
    with the worker so exceptions are logged to Sentry.
    """
    def send_to_sentry(job, *exc_info):
        client.captureException(
            exc_info=exc_info,
            extra={
                'job_id': job.id,
                'func': job.func_name,
                'args': job.args,
                'kwargs': job.kwargs,
                'description': job.description,
            })

    worker.push_exc_handler(send_to_sentry)
```

**Comment by dcramer** [comment]
@gsakkis this is more about contextual state that we need to bind. in Celery we do it by hooking various signals, which I kind of assume exist in most reasonable platforms these days. If we back out the sys.argv change it at least solves your regression, but it doesnt take advantage of the new transaction capabilities that Sentry offers.

**Comment by gsakkis** [comment]
Great, thanks for the quick fix!
