### ISSUE TITLE
Event values for captureException are reversed

### ISSUE THREAD

**Issue by johansteffner** [getsentry/raven-python#898]
# Problem

When handling exceptions thrown from previous exceptions the order of the chain sent to sentry is incorrect.

See attached screenshots for the Sentry UI for an error thrown by this code:
```python
class FirstError(Exception):
    pass


class SecondError(Exception):
    pass


class ThirdError(Exception):
    pass

…

try:
    raise FirstError()
except Exception as e:
    try:
        raise SecondError() from e
    except Exception as e:
        raise ThirdError() from e
```

# Screenshots

![screen shot 2016-10-27 at 13 26 11](https://cloud.githubusercontent.com/assets/623271/19765555/53f7d868-9c49-11e6-849e-16997713643b.png)

![screen shot 2016-10-27 at 13 26 21](https://cloud.githubusercontent.com/assets/623271/19765562/59b3b0f6-9c49-11e6-9dea-3ea116fd6265.png)

# Expected outcome

* The event list in sentry should show `ThirdError` as title
* The order of the events should, while sorted with most recent first, be:
  * `ThirdError`
  * `SecondError`
  * `FirstError`

**Comment by dcramer** [comment]
We'll need to confirm order is correct. IIRC order of exceptions is reversed from order of frames, and we seem to not even document what is expected.

**Comment by johansteffner** [comment]
Yes, i tried to find something to back up my assumptions with. This [closed issue](https://github.com/getsentry/sentry/pull/3963) is supporting the corrected order in #899.

**Comment by johansteffner** [comment]
[This documentation](https://github.com/getsentry/sentry/blob/3240d8fb53be5c0bda20bf183dba522313946382/src/sentry/interfaces/exception.py#L180-L181) confirms the order.

**Comment by dcramer** [comment]
I'm also pushing out an update to docs which describes this

**Comment by johansteffner** [comment]
Great! Have a nice weekend!

**Comment by johansteffner** [comment]
@dcramer do you have an ETA when there will be a release including this?
