### ISSUE TITLE
Ability to set Sentry options in raven.contrib.flask 

### ISSUE THREAD

**Issue by jakubczaplicki** [getsentry/raven-python#900]
https://docs.sentry.io/clients/node/config/ tells us that we can set options such as `release`, `tags`, or `environment`. How can I set those options in raven.contrib.flask ?

**Comment by dcramer** [comment]
@jakubczaplicki you can use SENTRY_OPTIONS to pass any of the standard configuration. I'm getting the Flask docs updated to reflect that:

https://docs.sentry.io/clients/python/advanced/#client-arguments

**Comment by jakubczaplicki** [comment]
I guess you meant `SENTRY_CONFIG` (not `SENTRY_OPTIONS`), right ?

**Comment by dcramer** [comment]
Sorry yeah ``SENTRY_CONFIG``
