### ISSUE TITLE
Celery broke latest sentry installation

### ISSUE THREAD

**Issue by gek0** [getsentry/raven-python#902]
I've recently updated my sentry installation from 8.9.0 to 8.10.0 and performed schema upgrade/migration.

After restart, sentry-web is working fine but sentry-workers and sentry-cron are reporting this error.
How can I resolve this issue?
```
Error: No such command "celery".
Usage: sentry [OPTIONS] COMMAND [ARGS]...
```

**Comment by gek0** [comment]
Resolved, found in changelog that it was deprecated in 8.5.0

**Comment by mattrobenolt** [comment]
:) It also should have yelled loudly from the CLI when you used the old commands.

**Comment by mattrobenolt** [comment]
Also, this was completely wrong repository. :(
