### ISSUE TITLE
`sentry_version` clarification

### ISSUE THREAD

**Issue by ye** [getsentry/raven-python#908]
According to the release log from 1.0.4 of raven-python, `sentry_version` is the expected sentry server version. [1]

However, in the unit tests and the latest official sentry Dockerfile as of today, that SENTRY_VERSION has been inconsistent specified: Dockerfile has it defined as '8.10' [2] unit tests in Sentry server has it fixated at '2' [3] and in `raven-python` fixated at '6'. [4]

So those brought up my question: does `sentry_version` actually matter in the header that raven client sent in the header? If not, can we ignore it from the header?

[1] https://github.com/getsentry/raven-python/blob/master/CHANGES#L579
[2] https://github.com/getsentry/docker-sentry/blob/master/8.10/Dockerfile#L56
[3] https://github.com/getsentry/raven-python/blob/master/tests/base/tests.py#L195
[4] https://github.com/getsentry/sentry/blob/master/tests/sentry/web/api/tests.py#L83

**Comment by mattrobenolt** [comment]
`sentry_version` in this context is the API version. It's not the version of the server itself or client. It's just for API compatibility.

**Comment by ye** [comment]
Ok thanks. So what's the latest correct API version?

**Comment by ye** [comment]
@mattrobenolt [Here](https://docs.sentry.io/api/) it says API version is `v0`?

**Comment by mattrobenolt** [comment]
haha, sorry, there are lots of things here. We have an explicit version of the API for event submission that is entirely different from the actual REST API. If that makes sense. This version literally only affects event submission for clients.

**Comment by ye** [comment]
Ok, so the latest `sentry_version` that raven-python sends in the header should be '6'? 

https://github.com/getsentry/raven-python/blob/master/CHANGES#L320

**Comment by mattrobenolt** [comment]
Correct. raven-python sends version 6: https://github.com/getsentry/raven-python/blob/master/raven/base.py#L142

Though the latest version is actually 7, we just don't require version 7 I guess for raven-python.
