### ISSUE TITLE
Access to sys.argv can fail for embedded interpreters

### ISSUE THREAD

**Issue by byjott** [getsentry/raven-python#918]
The initialization of ``raven.base.Client`` accesses ``sys.argv`` in some cases. Unfortunately, this attribute is not set for embedded python interpreters (i.e. for python is started from C/C++), and an ``AttributeError`` is raised.
I propose to replace ``sys.argv`` by ``getattr(sys, 'argv', [])`` instead to handle that case gracefully.

**Comment by dcramer** [comment]
@byjott would you mind taking a stab at a PR here? bonus for tests ;)
