### ISSUE TITLE
Memory leak on each raven.Client()

### ISSUE THREAD

**Issue by lachauj** [getsentry/raven-python#944]
To make it easier, I declared raven.Client() only when I needed it. 
Even if I delete the object at the end, I can see a huge memory leak on each call.

Simple sample code to reproduce the issue:

```python
from raven import Client

while True:
    cl = Client(url)
    del cl
```

I am using Python 2.7 on Windows

**Comment by dcramer** [comment]
It's because its injecting error handlers that are likely not weakrefs (and may not be safe to make such). You should declare it once rather than repeatedly on-demand.

**Comment by lazka** [comment]
@lachauj  Calling `cl.context.deactivate()` fixes the leak here.
