### ISSUE TITLE
[feature request]Add support for global context variables

### ISSUE THREAD

**Issue by biblicabeebli** [getsentry/raven-python#947]
Sticking tags etc. into a context is obnoxious when dealing with threads.  It would be great if there was a way to add a global tags that did not need to be reactivated all the time.

I expect the best policy when encountering collisions would be for thread-local tags to override global tags.

**Comment by dcramer** [comment]
@biblicabeebli you can pass tags to Client() at runtime, which are global

**Comment by biblicabeebli** [comment]
Sweet, that will save me _a lot_ of work.

This feature is not documented in the [Sentry python docs](https://docs.sentry.io/clients/python/), and it is obfuscated in the source code for the raven client because it is not a "real" kwarg, and gets swallowed by the `**options` kwarg packing.

I also could not find anything helpful by googling for phrases like "sentry global tags python", "sentry context multiple threads python", or really anything like that.  New feature request: surface this feature?
