### ISSUE TITLE
How to see the Referrer URL in Sentry

### ISSUE THREAD

**Issue by eskhool** [getsentry/raven-python#956]
This could be my having missed it in the docs or in sentry itself, but I am unable to see which URL sent us to the URL causing the error. How would one go about capturing that using Sentry?
Thx

**Comment by dcramer** [comment]
This comes from HTTP context, which generally we automatically pick up from frameworks. 

https://docs.sentry.io/clientdev/interfaces/http/

**Comment by eskhool** [comment]
Well, django provides this as request.META.HTTP_REFERER but I don't see this anywhere in the event ...sorry if I missed this somewhere

**Comment by dcramer** [comment]
@eskhool something is either preventing our middleware from loading, you're using an old version, or the request object is not available at the time of the exception. I would check those things, as by default we inject everything required in order to capture this information automatically.
