### ISSUE TITLE
Request is not logged to sentry using the default django middleware

### ISSUE THREAD

**Issue by teeberg** [getsentry/raven-python#957]
It looks like there's code to automatically track requests and send them to sentry even when you don't pass `extra={'request': request}` to the logging call. However, it's not working for us because of the following:

The request gets set in local thread storage [here](https://github.com/getsentry/raven-python/blob/6ead8beb09d6d40b91be213580dd4d9d5bd72f37/raven/contrib/django/middleware/__init__.py#L105), where `self.thread` is an instance of `raven.contrib.django.middleware.SentryMiddleware`, and then read [here](https://github.com/getsentry/raven-python/blob/6ead8beb09d6d40b91be213580dd4d9d5bd72f37/raven/contrib/django/client.py#L258), where `SentryLogMiddleware.thread` is a `property` object, which is not what it was set on, and thus leads to `request` being `None`.

Doing some git blaming, I think this broke in https://github.com/getsentry/raven-python/commit/c3e504a0bf77deb9a79bd841e9cacc62c8127901, where `SentryMiddleware.thread` was changed from a thread-local class variable to a property

This is with raven-python 5.32.0

**Comment by dcramer** [comment]
Not sure how we fucked this one up, but I'll dig into it as glancing over you're definitely right.

**Comment by teeberg** [comment]
That was crazy fast! Thank you for the really quick fix!! :)
