### ISSUE TITLE
Ignoring exceptions on Flask does not work anymore with child exceptions

### ISSUE THREAD

**Issue by noirbizarre** [getsentry/raven-python#963]
#821 is a fundamental behavior change on change on exception handling which is not documented into the changelog.
The main consequence is that child exception are now reported to sentry unless you list all child exceptions.
On a big project, this is really painful and this ends with a sentry massive polution with unwanted expection.

On flask, as handled HTTP errors are exception-based, I have to switch from ignoring HTTPException to ignoring every child, the werkzeug ones and the app children ones. In a case where the app can also host plugins raising custom exception, it becomes a nightmare.

**Comment by dcramer** [comment]
@noirbizarre you simply mean in that it is doing string vs class matching now?

**Comment by noirbizarre** [comment]
Yes, `isinstance()` has been replaced by string matching.
I'm beginning a PR to support both, any objection before I start ?

**Comment by dcramer** [comment]
@noirbizarre not opposed at all -- that was going to be my suggestion

**Comment by noirbizarre** [comment]
Great ! 👍
