### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by beruic** [getsentry/raven-python#985]
I'm a bit confused whether to use version 6.0.0 or 5.33.0 (which was release last). I cannot find documentation on the difference.

**Comment by mattrobenolt** [comment]
Well, as semantic versioning implies, these are two different major versions. 5.33.0 was pushed out yesterday with a bug fix for 5.x version, while 6.x is a larger API breaking version. 6.0.0 already has the bug fix that was needed for 5.33.0. 

So yes, 5.33.0 is newer, but on a new project, just use 6.0.0.

**Comment by beruic** [comment]
Still, is there anything I should be aware of on my old Django project before upgrading from 5.33.0 to 6.0.0?

**Comment by mattrobenolt** [comment]
Most likely no, but here's CHANGES: https://github.com/getsentry/raven-python/blob/master/CHANGES

Also would maybe be worth just testing, as always. :)

**Comment by beruic** [comment]
Super! It would be nice however if the readme referred to thi changelog. Also 5.33.0 is not mentioned in it.
