### ISSUE TITLE
raven.exceptions.InvalidGitRepository: Cannot identify HEAD for git repository

### ISSUE THREAD

**Issue by neerajgupta2407** [getsentry/raven-python#986]
HI, I am usind Django-edge.
https://django-edge.readthedocs.io/en/latest/

I am trying to install Raven but it giving error: 
raven.exceptions.InvalidGitRepository: Cannot identify HEAD for git repository at /home/neeraj/codes/envision_code/src/envision_code/settings

Since my settings file is in sub folder, so its giving error..
How should i rectify this?

**Comment by mattrobenolt** [comment]
Hey @neerajgupta2407, I'm assuming you're having an issue from the documentation suggestion of:

```python
RAVEN_CONFIG = {
    'dsn': 'https://xxx:yyy@sentry.io/1',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),
}
```

In which case it's erroring at the `raven.fetch_git_sha` call. You should change this to accommodate your needs. This is merely an example. You'd want to point `fetch_git_sha()` at the root of the repository where your `.git` folder is.
